#import "TGLocalization.h"

static NSString * const TGLanguageDefaultsKey = @"TelegraphicaLanguageCode";

NSString *TGLanguageCode(void) {
    NSString *code = [[NSUserDefaults standardUserDefaults] stringForKey:TGLanguageDefaultsKey];
    if ([code isEqualToString:@"ru"] || [code isEqualToString:@"be"] || [code isEqualToString:@"en"]) {
        return code;
    }
    return @"ru";
}
void TGSetLanguageCode(NSString *code) {
    NSString *validated = ([code isEqualToString:@"ru"] || [code isEqualToString:@"be"] || [code isEqualToString:@"en"]) ? code : @"ru";
    [[NSUserDefaults standardUserDefaults] setObject:validated forKey:TGLanguageDefaultsKey];
    [[NSUserDefaults standardUserDefaults] synchronize];
}

NSString *TGLoc(NSString *key) {
    if (![key isKindOfClass:[NSString class]]) {
        return @"";
    }

    NSString *language = TGLanguageCode();
    NSDictionary *ru = [NSDictionary dictionaryWithObjectsAndKeys:
                        @"Чаты", @"chats",
                        @"Назад", @"back",
                        @"Мастерская", @"workshop.title",
                        @"Открыть Мастерскую", @"workshop.openTooltip",
                        @"Доступно", @"workshop.available",
                        @"Установлено", @"workshop.installed",
                        @"Обновления", @"workshop.updates",
                        @"Обновить каталог", @"workshop.refreshCatalog",
                        @"Обновление каталога...", @"workshop.refreshing",
                        @"Игры", @"workshop.games",
                        @"Версия", @"workshop.version",
                        @"Установить", @"workshop.install",
                        @"Установка...", @"workshop.installing",
                        @"Игра установлена", @"workshop.installComplete",
                        @"Открыть", @"workshop.open",
                        @"Обновить", @"workshop.update",
                        @"Удалить", @"workshop.remove",
                        @"Повторить", @"workshop.retry",
                        @"Установленная версия:", @"workshop.installedVersion",
                        @"Не установлено", @"workshop.notInstalled",
                        @"В этом разделе пока ничего нет.", @"workshop.empty",
                        @"Каталог временно недоступен. Установленные игры продолжат работать офлайн.", @"workshop.catalogUnavailable",
                        @"Каталог недоступен; показаны локальные данные.", @"workshop.offlineHint",
                        @"Модулей: %lu", @"workshop.itemsCount",
                        @"Не удалось выполнить действие.", @"workshop.unknownError",
                        @"Удалить игру?", @"workshop.removeConfirmTitle",
                        @"Можно сохранить прогресс или удалить игру вместе со всеми сохранениями. Открытая игра будет закрыта, а файлы удалятся после перезапуска Telegraphica.", @"workshop.removeConfirmMessage",
                        @"Удалить, сохранив прогресс", @"workshop.removeKeepData",
                        @"Удалить вместе с прогрессом", @"workshop.removeWithData",
                        @"Повреждённое сохранение отложено для диагностики. Начата новая игра.", @"game.save_recovered",
                        @"Компьютер", @"game.computer",
                        @"Два игрока", @"game.twoPlayers",
                        @"Легко", @"game.easy",
                        @"Средне", @"game.medium",
                        @"Сложно", @"game.hard",
                        @"Новый раунд", @"game.newRound",
                        @"Ничья", @"game.draw",
                        @"%@ победил", @"game.winner",
                        @"Ход: %@", @"game.turn",
                        @"Ничьи", @"game.draws",
                        @"Перезапустить", @"game.restart",
                        @"Время", @"game.time",
                        @"Победа", @"game.won",
                        @"Игра окончена", @"game.lost",
                        @"Новая игра", @"game.newGame",
                        @"Пауза", @"game.pause",
                        @"Продолжить", @"game.resume",
                        @"Пауза", @"game.paused",
                        @"Счёт", @"game.score",
                        @"Жизни", @"game.lives",
                        @"Отменить ход", @"game.undo",
                        @"Победы", @"game.wins",
                        @"Используйте стрелки или WASD", @"pacman.hint",
                        @"Точки", @"pacman.pellets",
                        @"Крестики-нолики", @"tictactoe.title",
                        @"Сапёр", @"minesweeper.title",
                        @"Выберите клетку", @"minesweeper.ready",
                        @"Очистите поле", @"minesweeper.playing",
                        @"Мины", @"minesweeper.mines",
                        @"Шашки", @"checkers.title",
                        @"Новая игра", @"checkers.new_game",
                        @"Красные победили", @"checkers.red_wins",
                        @"Чёрные победили", @"checkers.black_wins",
                        @"Продолжите взятие", @"checkers.continue_capture",
                        @"Ход красных", @"checkers.red_turn",
                        @"Ход чёрных", @"checkers.black_turn",
                        @"Красные", @"checkers.red",
                        @"Чёрные", @"checkers.black",
                        @"Косынка", @"solitaire.title",
                        @"Новая раздача", @"solitaire.new_deal",
                        @"Перетаскивайте карты или дважды нажмите, чтобы отправить карту в дом.", @"solitaire.hint",
                        @"Чаты закрыты", @"closedChats.title",
                        @"Выберите недавний личный диалог, чтобы продолжить общение.", @"closedChats.hint",
                        @"Все чаты", @"drawer.all",
                        @"Все чаты", @"drawer.all.tooltip",
                        @"Закреплённое сообщение", @"pinned.title",
                        @"Профиль", @"profile",
                        @"Настройки", @"settings",
                        @"Сообщение", @"message",
                        @"Сообщение", @"message.placeholder",
                        @"Вы", @"message.you",
                        @"Ответ", @"reply",
                        @"Ответ для %@", @"reply.to",
                        @"Ответ себе", @"reply.toSelf",
                        @"Переслано от %@", @"forwarded.from",
                        @"Оригинальное сообщение", @"message.original",
                        @"Изображение", @"media.image",
                        @"Видео", @"media.video",
                        @"GIF", @"media.gif",
                        @"Документ", @"media.document",
                        @"Медиа", @"media.media",
                        @"Медиа", @"media.center.title",
                        @"Информация о чате", @"media.center.windowTitle",
                        @"Стикер", @"media.sticker",
                        @"Голосовое сообщение", @"media.voice",
                        @"Видеосообщение", @"media.videoNote",
                        @"Сервисное сообщение", @"media.service",
                        @"Текст", @"media.text",
                        @"Прикрепить фото", @"attach.photo",
                        @"Прикрепить файл...", @"attach.file",
                        @"Стикеры", @"stickers",
                        @"Недавние стикеры", @"stickers.recent",
                        @"Недавние", @"stickers.recent.tab",
                        @"Недавн.", @"stickers.recent.short",
                        @"Избранное", @"stickers.favorites.tab",
                        @"Избр.", @"stickers.favorites.short",
                        @"Эмодзи", @"stickers.search.placeholder",
                        @"Удалить набор", @"stickers.removeSet",
                        @"Удал.", @"stickers.removeSet.short",
                        @"Голос", @"voice",
                        @"Отправить", @"send",
                        @"Отмена", @"cancel",
                        @"OK", @"ok",
                        @"Добавить подпись...", @"caption.placeholder",
                        @"Показывать уведомления", @"settings.notifications",
                        @"Звук уведомлений", @"settings.sound",
                        @"Бейдж непрочитанных в Dock", @"settings.badge",
                        @"Показывать текст сообщения", @"settings.preview",
                        @"Уведомлять, когда Telegraphica открыта", @"settings.whenActive",
                        @"Скрыть боковую панель", @"settings.drawer",
                        @"Показывать, когда собеседник печатает", @"settings.typing",
                        @"Категория", @"settings.theme.category",
                        @"Светлые темы", @"settings.theme.category.light",
                        @"Тёмные темы", @"settings.theme.category.dark",
                        @"Retro", @"settings.theme.category.oldSchool",
                        @"Экспериментальные", @"settings.theme.category.experimental",
                        @"Визуальные миры", @"settings.theme.category.visualWorlds",
                        @"Тема", @"settings.theme",
                        @"Оформление", @"settings.appearance",
                        @"Папка загрузок", @"settings.downloads",
                        @"Язык", @"settings.language",
                        @"Сообщения блоками", @"settings.messages.blocks",
                        @"Размер текста", @"settings.chatText",
                        @"Маленький", @"settings.chatText.small",
                        @"Обычный", @"settings.chatText.normal",
                        @"Крупный", @"settings.chatText.large",
                        @"Очень крупный", @"settings.chatText.veryLarge",
                        @"Проверить обновления", @"settings.update",
                        @"Диагностические логи", @"settings.logs",
                        @"О Telegraphica", @"settings.about",
                        @"Уведомления", @"settings.section.notifications",
                        @"Общие", @"settings.section.drawer",
                        @"Ресурсы", @"settings.section.resources",
                        @"Активные сессии", @"settings.section.sessions",
                        @"Интерфейс", @"settings.section.interface",
                        @"Файлы", @"settings.section.files",
                        @"Справка", @"settings.section.help",
                        @"Выберите папку, в которой будут сохраняться загруженные файлы", @"settings.downloads.help",
                        @"Устройства, на которых выполнен вход в этот аккаунт", @"settings.sessions.help",
                        @"Экономичный режим", @"settings.resources.economy",
                        @"Автозагрузка фото", @"settings.resources.photos",
                        @"Автозагрузка видео", @"settings.resources.videos",
                        @"Автозагрузка документов", @"settings.resources.documents",
                        @"Автовоспроизведение анимированных стикеров", @"settings.resources.autoplay",
                        @"Останавливать анимации, когда окно неактивно", @"settings.resources.stopInactive",
                        @"Максимальный размер автозагрузки", @"settings.resources.maxDownload",
                        @"Активных анимаций", @"settings.resources.maxAnimations",
                        @"Лимит медиакэша", @"settings.resources.cacheLimit",
                        @"Экономичный режим снижает автозагрузку, отключает лишние анимации и уменьшает кэш. Отдельные пункты можно менять вручную.", @"settings.resources.hint",
                        @"Открыть активные сессии", @"settings.sessions.open",
                        @"Обновить", @"settings.sessions.refresh",
                        @"Загрузка активных сессий...", @"settings.sessions.loading",
                        @"Сессии недоступны: %@", @"settings.sessions.failed",
                        @"Список сессий устарел. Обновляю...", @"settings.sessions.stale",
                        @"Активных устройств: %lu", @"settings.sessions.count",
                        @"Автозавершение неактивных сессий: %ld дн.", @"settings.sessions.ttl",
                        @"Последняя активность: %@", @"settings.sessions.lastActive",
                        @"Неизвестное устройство", @"settings.sessions.unknownDevice",
                        @"неизвестная ошибка", @"settings.sessions.unknownError",
                        @"Текущее устройство", @"settings.sessions.current",
                        @"Нет других активных сессий", @"settings.sessions.empty",
                        @"Выберите устройство для завершения", @"settings.sessions.selectDevice",
                        @"Завершить", @"settings.sessions.terminate",
                        @"Завершить сессию", @"settings.sessions.terminate.title",
                        @"Завершить сессию на устройстве «%@»?", @"settings.sessions.terminate.message",
                        @"Завершение сессии...", @"settings.sessions.terminating",
                        @"Сессия завершена.", @"settings.sessions.terminate.done",
                        @"Не удалось завершить сессию: %@", @"settings.sessions.terminate.failed",
                        @"Общие медиа и файлы", @"media.center.titleCard",
                        @"Новые элементы сверху. Обычный клик открывает превью; переход к сообщению доступен через правую кнопку.", @"media.center.hint",
                        @"Выберите чат, чтобы посмотреть медиа.", @"media.center.chooseChat",
                        @"Загрузка медиа...", @"media.center.loading",
                        @"Откройте чат сначала.", @"media.center.openChatFirst",
                        @"Медиа не найдены.", @"media.center.empty",
                        @"%lu элемент(ов), локальный кэш %@. Прокрутите вниз, чтобы загрузить ещё.", @"media.center.loadedStatus",
                        @"%lu элемент(ов), локальный кэш %@. Все найденные элементы загружены.", @"media.center.loadedStatus.done",
                        @"Загрузка ещё...", @"media.center.loadingMore",
                        @"Поиск медиа не удался: %@", @"media.center.failed",
                        @"Медиа", @"media.center.tab.media",
                        @"Файлы", @"media.center.tab.files",
                        @"Ссылки", @"media.center.tab.links",
                        @"Музыка", @"media.center.tab.music",
                        @"Голос", @"media.center.tab.voice",
                        @"GIF", @"media.center.tab.gif",
                        @"Опросы", @"media.center.tab.polls",
                        @"Группы", @"media.center.tab.groups",
                        @"%lu общих групп.", @"media.center.groups.loadedStatus",
                        @"Общие группы не найдены.", @"media.center.groups.empty",
                        @"Общие группы доступны только для личных чатов.", @"media.center.groups.privateOnly",
                        @"Без названия", @"media.center.group.untitled",
                        @"У этого элемента пока нет id файла.", @"media.center.noFileID",
                        @"Скачиваем медиа...", @"media.center.downloading",
                        @"Скачано %@", @"media.center.downloaded",
                        @"Ошибка скачивания: %@", @"media.center.downloadFailed",
                        @"Сначала скачайте этот элемент.", @"media.center.downloadBeforeOpen",
                        @"Не удалось открыть файл системным приложением.", @"media.center.openFailed",
                        @"Превью", @"media.center.preview",
                        @"Открыть файл", @"media.center.open",
                        @"Скачать", @"media.center.download",
                        @"Перейти к файлу", @"media.center.goToFile",
                        @"Удалить локальную копию", @"media.center.deleteLocal",
                        @"Для этого элемента нет превью. Используйте правую кнопку, чтобы скачать или открыть файл.", @"media.center.previewUnavailable",
                        @"Использование памяти", @"storage.open",
                        @"Использование памяти", @"storage.title",
                        @"Загрузка...", @"storage.loading",
                        @"Всего: %@", @"storage.total",
                        @"Файлы", @"storage.files",
                        @"База TDLib", @"storage.database",
                        @"Языковые пакеты", @"storage.language",
                        @"Логи", @"storage.logs",
                        @"Медиа и документы останутся в облаке Telegram, при необходимости их можно скачать заново.", @"storage.safeHint",
                        @"Очистить кэш", @"storage.clear",
                        @"Обновить", @"storage.refresh",
                        @"Статистика недоступна", @"storage.unavailable",
                        @"Очищаем кэш...", @"storage.clearing",
                        @"Не удалось очистить кэш", @"storage.clearFailed",
                        @"Кэш очищен. Обновлённый размер показан выше.", @"storage.clearDone",
                        @"Очистить кэш Telegraphica?", @"storage.confirm.title",
                        @"Скачанные медиа будут удалены с этого Mac, но останутся в Telegram. Авторизация и сообщения не будут затронуты.", @"storage.confirm.message",
                        @"Удалить локальные данные", @"settings.localData.delete",
                        @"Удалить локальные данные Telegraphica?", @"settings.localData.confirm.title",
                        @"Будут удалены локальная база TDLib, кэш, превью, черновики, диагностические логи и локальный ключ базы на этом Mac. Данные в облаке Telegram и файлы в Downloads не будут затронуты. После этого нужно будет войти заново.", @"settings.localData.confirm.message",
                        @"Локальные данные удалены. Telegraphica вернётся к экрану входа.", @"settings.localData.done",
                        @"Локальные данные удалены, но часть очистки не завершилась: %@", @"settings.localData.partial",
                        @"Удаление локальных данных...", @"settings.localData.busy",
                        @"Закрыть", @"close",
                        @"Новое сообщение", @"notification.hiddenPreview",
                        @"Начать запись голоса?", @"voice.permission.title",
                        @"Telegraphica сможет использовать микрофон для записи голосовых сообщений. Запись начинается только после нажатия кнопки голоса.", @"voice.permission.message",
                        @"Записывается...", @"voice.recording",
                        @"Нажмите кнопку голоса ещё раз, чтобы остановить запись", @"voice.stopHint",
                        @"Отправка...", @"sending",
                        @"Отметить прочитанным", @"chat.markRead",
                        @"Прочитать все чаты", @"chat.readAll",
                        @"Закрепить диалог", @"chat.pin",
                        @"Открепить диалог", @"chat.unpin",
                        @"Включить локальные уведомления", @"chat.notifications.enable",
                        @"Отключить уведомления", @"chat.notifications.mute",
                        @"На 1 час", @"chat.notifications.hour",
                        @"На 1 день", @"chat.notifications.day",
                        @"Навсегда", @"chat.notifications.forever",
                        @"Закрепить сообщение", @"message.pin",
                        @"Открепить сообщение", @"message.unpin",
                        @"Ответить", @"message.reply",
                        @"Переслать...", @"message.forward",
                        @"Переслать в Избранное", @"message.forward.saved",
                        @"Открыть комментарии", @"message.comments.open",
                        @"Прокомментировать", @"message.comments.add",
                        @"%ld комментарий", @"message.comments.count.one",
                        @"%ld комментариев", @"message.comments.count.many",
                        @"комментарии", @"message.comments.threadSuffix",
                        @"Комментарии", @"message.comments.threadTitle",
                        @"Кто прочитал", @"message.whoRead",
                        @"Кто прочитал это сообщение", @"message.viewers.title",
                        @"Загружаем читателей...", @"message.viewers.loading",
                        @"Читатели недоступны для этого сообщения.", @"message.viewers.unavailable",
                        @"Никто ещё не прочитал", @"message.viewers.empty",
                        @"Вход ещё не готов", @"message.viewers.signInUnavailable",
                        @"Неизвестно", @"message.viewers.unknown",
                        @"Нет данных", @"message.viewers.noData",
                        @"Ещё реакции", @"message.reactions.more",
                        @"Копировать текст", @"message.copyText",
                        @"Копировать неотправленный текст", @"message.copyUnsentText",
                        @"Повторить отправку", @"message.retrySend",
                        @"Отправка не удалась", @"message.sendFailed",
                        @"Повторить отправку?", @"message.retry.confirm.title",
                        @"Сообщение могло быть отправлено, но Telegraphica не получила подтверждение. Повтор может создать дубль.", @"message.retry.confirm.message",
                        @"Подтверждено частей: %lu из %lu. Повтор может создать дубли уже отправленных частей.", @"message.retry.confirm.partial",
                        @"Повторяем отправку...", @"message.retry.sending",
                        @"Сообщение отправлено", @"message.retry.sent",
                        @"Повтор не удался", @"message.retry.failed",
                        @"Скачать медиа", @"message.downloadMedia",
                        @"Скачать документ", @"message.downloadDocument",
                        @"Скачать", @"message.download.action",
                        @"Редактировать", @"message.edit",
                        @"Редактировать сообщение", @"message.edit.title",
                        @"Исправьте текст и сохраните изменения.", @"message.edit.hint",
                        @"Сохранить", @"message.edit.save",
                        @"Удалить сообщение", @"message.delete",
                        @"Удалить сообщение?", @"message.delete.title",
                        @"Это действие нельзя отменить.", @"message.delete.hint",
                        @"Удалить", @"message.delete.action",
                        @"Удалить у меня", @"message.delete.self",
                        @"Удалить у всех", @"message.delete.everyone",
                        @"Голосовать", @"message.poll.vote",
                        @"Создать опрос...", @"poll.create.menu",
                        @"Создать опрос", @"poll.create.title",
                        @"Введите вопрос и варианты ответа. Каждый вариант должен быть на отдельной строке.", @"poll.create.hint",
                        @"Вопрос", @"poll.create.question",
                        @"Варианты", @"poll.create.options",
                        @"Несколько ответов", @"poll.create.multiple",
                        @"Анонимный опрос", @"poll.create.anonymous",
                        @"Отправляем опрос...", @"poll.create.sending",
                        @"Опрос отправлен", @"poll.create.sent",
                        @"Не удалось отправить опрос", @"poll.create.failed",
                        @"Не удалось создать опрос", @"poll.create.error.title",
                        @"Введите вопрос.", @"poll.create.error.question",
                        @"Добавьте минимум два разных варианта.", @"poll.create.error.options",
                        @"Вариант %lu", @"message.poll.optionFallback",
                        @"Вариантов нет", @"message.poll.noOptions",
                        @"Отправляем голос...", @"message.poll.sending",
                        @"Голос учтён", @"message.poll.sent",
                        @"Не удалось проголосовать", @"message.poll.failed",
                        @"Подтвердить выбор", @"message.poll.submit",
                        @"Выберите варианты и подтвердите", @"message.poll.multipleHint",
                        @"закрыт", @"message.poll.closed",
                        @"quiz", @"message.poll.quiz",
                        @"%ld голос", @"message.poll.votes.one",
                        @"%ld голосов", @"message.poll.votes.many",
                        @"Поиск чатов", @"search.chats.title",
                        @"Чат, группа, человек", @"search.chats.placeholder",
                        @"Недавние чаты появятся здесь", @"search.chats.emptyRecent",
                        @"Чаты не найдены", @"search.chats.empty",
                        @"Недавние чаты. Введите запрос, чтобы найти чат, группу или человека.", @"search.chats.recent",
                        @"Загружаем недавние чаты...", @"search.chats.loadingRecent",
                        @"Ищем чаты...", @"search.chats.searching",
                        @"Загружено совпадений: %lu. Ищем дальше...", @"search.chats.loadedSearching",
                        @"Найдено чатов: %lu", @"search.chats.found",
                        @"Поиск не удался: %@", @"search.chats.failed",
                        @"Загруженных чатов пока нет", @"search.chats.noLoaded",
                        @"Открыть чат", @"search.chats.openHint",
                        @"Чат", @"search.chats.fallbackChat",
                        @"Избранное", @"savedMessages",
                        @"Новая версия Telegraphica", @"update.title",
                        @"Открыть страницу загрузки", @"update.open",
                        @"Не сейчас", @"update.later",
                        @"Скачать обновление", @"update.download",
                        @"Обновлений нет", @"update.none",
                        @"Установлена версия %@", @"update.noneMessage",
                        @"Доступна версия %@. Скачать установщик обновления?", @"update.availableMessage",
                        @"Не удалось проверить обновления: %@", @"update.failed",
                        @"Обновление скачано", @"update.downloaded.title",
                        @"Файл сохранён: %@", @"update.downloaded.message",
                        @"Открыть установщик", @"update.downloaded.open",
                        @"Не удалось скачать обновление", @"update.download.failed.title",
                        @"Ошибка загрузки: %@. Можно открыть страницу релиза и скачать файл вручную.", @"update.download.failed.message",
                        @"Профиль", @"profile.title",
                        @"Профиль", @"profile.fallback",
                        @"О себе", @"profile.about",
                        @"Аккаунт", @"profile.account",
                        @"Имя пользователя", @"profile.username",
                        @"Телефон", @"profile.phone",
                        @"Telegram ID", @"profile.id",
                        @"Выйти", @"profile.logout",
                        @"Обновить профиль", @"profile.refresh",
                        @"Войти", @"login.title",
                        @"Введите номер телефона, связанный с аккаунтом Telegram, вместе с кодом страны.", @"login.phone.hint",
                        @"Номер телефона", @"login.phone.label",
                        @"Введите код", @"login.code.title",
                        @"Код придёт в Telegram. Введите его здесь, чтобы продолжить вход.", @"login.code.hint",
                        @"Код входа", @"login.code.label",
                        @"Двухэтапная аутентификация", @"login.password.title",
                        @"Введите облачный пароль Telegram. Telegraphica не записывает его в логи.", @"login.password.hint",
                        @"Пароль", @"login.password.label",
                        @"Отправить", @"login.send",
                        @"Отправка...", @"login.sending",
                        @"Логи", @"login.logs",
                        @"Статус", @"login.status",
                        @"Подключение", @"login.connecting.title",
                        @"Telegraphica устанавливает безопасное соединение с Telegram. Это может занять несколько секунд.", @"login.connecting.hint",
                        @"Завершаем предыдущую сессию и готовим новый вход.", @"login.recovering.hint",
                        @"Повторить", @"login.retry",
                        @"Не удалось подготовить вход", @"login.config.title",
                        @"В этой сборке отсутствует внутренняя конфигурация подключения. Подробности доступны в логах.", @"login.config.missing",
                        @"Проверьте номер телефона и попробуйте снова.", @"login.error.phone",
                        @"Этот код не принят. Проверьте Telegram и попробуйте снова.", @"login.error.code",
                        @"Этот пароль не принят. Попробуйте снова.", @"login.error.password",
                        @"Не удалось войти. Попробуйте снова.", @"login.error.general",
                        @"Введите номер телефона, чтобы продолжить.", @"login.empty.phone",
                        @"Введите код входа из Telegram.", @"login.empty.code",
                        @"Введите пароль двухэтапной аутентификации.", @"login.empty.password",
                        @"Нет соединения. Подробности доступны в логах.", @"login.connection.unavailable",
                        @"О Telegraphica", @"about.title",
                        @"Версия %@ (%@)", @"about.version",
                        @"Все права защищены.", @"about.rights",
                        @"Для Intel Mac с OS X 10.8–macOS 10.13.\nОсновная разработка и проверка — на OS X 10.9: сделаем скевоморфичные системы снова великими.\nНовые macOS и Apple Silicon — без гарантий; общая поддержка Intel-приложений Rosetta заканчивается после macOS 27.", @"about.compatibility",
                        @"Автор: Yura Menschikov", @"about.author",
                        @"Проект на GitHub", @"about.project",
                        @"Канал Telegraphica в Telegram", @"about.channel",
                        @"Открыть канал Telegraphica", @"about.channel.open.title",
                        @"Где открыть канал @macos_telegraphica?", @"about.channel.open.message",
                        @"В Telegraphica", @"about.channel.open.app",
                        @"В браузере", @"about.channel.open.browser",
                        @"Отмена", @"common.cancel",
                        @"Открываю канал Telegraphica...", @"about.channel.opening",
                        @"Канал Telegraphica открыт.", @"about.channel.opened",
                        @"Не удалось открыть канал в Telegraphica.", @"about.channel.open.failed",
                        @"Можно открыть канал в браузере.", @"about.channel.open.browserFallback",
                        nil];
    NSDictionary *be = [NSDictionary dictionaryWithObjectsAndKeys:
                        @"Чаты", @"chats",
                        @"Назад", @"back",
                        @"Майстэрня", @"workshop.title",
                        @"Адкрыць Майстэрню", @"workshop.openTooltip",
                        @"Даступна", @"workshop.available",
                        @"Усталявана", @"workshop.installed",
                        @"Абнаўленні", @"workshop.updates",
                        @"Абнавіць каталог", @"workshop.refreshCatalog",
                        @"Абнаўленне каталога...", @"workshop.refreshing",
                        @"Гульні", @"workshop.games",
                        @"Версія", @"workshop.version",
                        @"Усталяваць", @"workshop.install",
                        @"Усталяванне...", @"workshop.installing",
                        @"Гульня ўсталявана", @"workshop.installComplete",
                        @"Адкрыць", @"workshop.open",
                        @"Абнавіць", @"workshop.update",
                        @"Выдаліць", @"workshop.remove",
                        @"Паўтарыць", @"workshop.retry",
                        @"Усталяваная версія:", @"workshop.installedVersion",
                        @"Не ўсталявана", @"workshop.notInstalled",
                        @"У гэтым раздзеле пакуль нічога няма.", @"workshop.empty",
                        @"Каталог часова недаступны. Усталяваныя гульні працягнуць працаваць афлайн.", @"workshop.catalogUnavailable",
                        @"Каталог недаступны; паказаны лакальныя даныя.", @"workshop.offlineHint",
                        @"Модуляў: %lu", @"workshop.itemsCount",
                        @"Не атрымалася выканаць дзеянне.", @"workshop.unknownError",
                        @"Выдаліць гульню?", @"workshop.removeConfirmTitle",
                        @"Можна захаваць прагрэс або выдаліць гульню разам з усімі захаваннямі. Адкрытая гульня будзе закрыта, а файлы выдаляцца пасля перазапуску Telegraphica.", @"workshop.removeConfirmMessage",
                        @"Выдаліць, захаваўшы прагрэс", @"workshop.removeKeepData",
                        @"Выдаліць разам з прагрэсам", @"workshop.removeWithData",
                        @"Пашкоджанае захаванне адкладзена для дыягностыкі. Пачата новая гульня.", @"game.save_recovered",
                        @"Камп'ютар", @"game.computer",
                        @"Два гульцы", @"game.twoPlayers",
                        @"Лёгка", @"game.easy",
                        @"Сярэдне", @"game.medium",
                        @"Складана", @"game.hard",
                        @"Новы раўнд", @"game.newRound",
                        @"Нічыя", @"game.draw",
                        @"%@ перамог", @"game.winner",
                        @"Ход: %@", @"game.turn",
                        @"Нічыі", @"game.draws",
                        @"Перазапусціць", @"game.restart",
                        @"Час", @"game.time",
                        @"Перамога", @"game.won",
                        @"Гульня скончана", @"game.lost",
                        @"Новая гульня", @"game.newGame",
                        @"Паўза", @"game.pause",
                        @"Працягнуць", @"game.resume",
                        @"Паўза", @"game.paused",
                        @"Лік", @"game.score",
                        @"Жыцці", @"game.lives",
                        @"Адмяніць ход", @"game.undo",
                        @"Перамогі", @"game.wins",
                        @"Кіруйце стрэлкамі або WASD", @"pacman.hint",
                        @"Кропкі", @"pacman.pellets",
                        @"Крыжыкі-нулікі", @"tictactoe.title",
                        @"Сапёр", @"minesweeper.title",
                        @"Выберыце клетку", @"minesweeper.ready",
                        @"Ачысціце поле", @"minesweeper.playing",
                        @"Міны", @"minesweeper.mines",
                        @"Шашкі", @"checkers.title",
                        @"Новая гульня", @"checkers.new_game",
                        @"Чырвоныя перамаглі", @"checkers.red_wins",
                        @"Чорныя перамаглі", @"checkers.black_wins",
                        @"Працягніце ўзяцце", @"checkers.continue_capture",
                        @"Ход чырвоных", @"checkers.red_turn",
                        @"Ход чорных", @"checkers.black_turn",
                        @"Чырвоныя", @"checkers.red",
                        @"Чорныя", @"checkers.black",
                        @"Касынка", @"solitaire.title",
                        @"Новая раздача", @"solitaire.new_deal",
                        @"Перацягвайце карты або двойчы націсніце, каб адправіць карту ў дом.", @"solitaire.hint",
                        @"Чаты закрыты", @"closedChats.title",
                        @"Выберыце нядаўні асабісты дыялог, каб працягнуць размову.", @"closedChats.hint",
                        @"Усе чаты", @"drawer.all",
                        @"Усе чаты", @"drawer.all.tooltip",
                        @"Замацаванае паведамленне", @"pinned.title",
                        @"Профіль", @"profile",
                        @"Налады", @"settings",
                        @"Паведамленне", @"message",
                        @"Паведамленне", @"message.placeholder",
                        @"Вы", @"message.you",
                        @"Адказ", @"reply",
                        @"Адказ для %@", @"reply.to",
                        @"Адказ сабе", @"reply.toSelf",
                        @"Пераслана ад %@", @"forwarded.from",
                        @"Арыгінальнае паведамленне", @"message.original",
                        @"Выява", @"media.image",
                        @"Відэа", @"media.video",
                        @"GIF", @"media.gif",
                        @"Дакумент", @"media.document",
                        @"Медыя", @"media.media",
                        @"Медыя", @"media.center.title",
                        @"Інфармацыя пра чат", @"media.center.windowTitle",
                        @"Стыкер", @"media.sticker",
                        @"Галасавое паведамленне", @"media.voice",
                        @"Відэапаведамленне", @"media.videoNote",
                        @"Сэрвіснае паведамленне", @"media.service",
                        @"Тэкст", @"media.text",
                        @"Прымацаваць фота", @"attach.photo",
                        @"Прымацаваць файл...", @"attach.file",
                        @"Стыкеры", @"stickers",
                        @"Нядаўнія стыкеры", @"stickers.recent",
                        @"Нядаўнія", @"stickers.recent.tab",
                        @"Нядаўн.", @"stickers.recent.short",
                        @"Абранае", @"stickers.favorites.tab",
                        @"Абр.", @"stickers.favorites.short",
                        @"Эмодзі", @"stickers.search.placeholder",
                        @"Выдаліць набор", @"stickers.removeSet",
                        @"Выд.", @"stickers.removeSet.short",
                        @"Голас", @"voice",
                        @"Адправіць", @"send",
                        @"Скасаваць", @"cancel",
                        @"OK", @"ok",
                        @"Дадаць подпіс...", @"caption.placeholder",
                        @"Паказваць апавяшчэнні", @"settings.notifications",
                        @"Гук апавяшчэнняў", @"settings.sound",
                        @"Бэйдж непрачытаных у Dock", @"settings.badge",
                        @"Паказваць тэкст паведамлення", @"settings.preview",
                        @"Апавяшчаць, калі Telegraphica адкрыта", @"settings.whenActive",
                        @"Схаваць бакавую панэль", @"settings.drawer",
                        @"Паказваць, калі суразмоўца друкуе", @"settings.typing",
                        @"Катэгорыя", @"settings.theme.category",
                        @"Светлыя тэмы", @"settings.theme.category.light",
                        @"Цёмныя тэмы", @"settings.theme.category.dark",
                        @"Retro", @"settings.theme.category.oldSchool",
                        @"Эксперыментальныя", @"settings.theme.category.experimental",
                        @"Візуальныя светы", @"settings.theme.category.visualWorlds",
                        @"Тэма", @"settings.theme",
                        @"Афармленне", @"settings.appearance",
                        @"Папка загрузак", @"settings.downloads",
                        @"Мова", @"settings.language",
                        @"Паведамленні блокамі", @"settings.messages.blocks",
                        @"Памер тэксту", @"settings.chatText",
                        @"Малы", @"settings.chatText.small",
                        @"Звычайны", @"settings.chatText.normal",
                        @"Вялікі", @"settings.chatText.large",
                        @"Вельмі вялікі", @"settings.chatText.veryLarge",
                        @"Праверыць абнаўленні", @"settings.update",
                        @"Дыягнастычныя логі", @"settings.logs",
                        @"Пра Telegraphica", @"settings.about",
                        @"Апавяшчэнні", @"settings.section.notifications",
                        @"Агульныя", @"settings.section.drawer",
                        @"Рэсурсы", @"settings.section.resources",
                        @"Актыўныя сеансы", @"settings.section.sessions",
                        @"Інтэрфейс", @"settings.section.interface",
                        @"Файлы", @"settings.section.files",
                        @"Даведка", @"settings.section.help",
                        @"Выберыце папку, у якой будуць захоўвацца спампаваныя файлы", @"settings.downloads.help",
                        @"Прылады, на якіх выкананы ўваход у гэты акаўнт", @"settings.sessions.help",
                        @"Эканомны рэжым", @"settings.resources.economy",
                        @"Аўтазагрузка фота", @"settings.resources.photos",
                        @"Аўтазагрузка відэа", @"settings.resources.videos",
                        @"Аўтазагрузка дакументаў", @"settings.resources.documents",
                        @"Аўтапрайграванне аніміраваных стыкераў", @"settings.resources.autoplay",
                        @"Спыняць анімацыі, калі акно неактыўнае", @"settings.resources.stopInactive",
                        @"Максімальны памер аўтазагрузкі", @"settings.resources.maxDownload",
                        @"Актыўных анімацый", @"settings.resources.maxAnimations",
                        @"Ліміт медыякэшу", @"settings.resources.cacheLimit",
                        @"Эканомны рэжым памяншае аўтазагрузку, адключае лішнія анімацыі і зніжае памер кэшу. Асобныя пункты можна змяняць уручную.", @"settings.resources.hint",
                        @"Адкрыць актыўныя сеансы", @"settings.sessions.open",
                        @"Абнавіць", @"settings.sessions.refresh",
                        @"Загрузка актыўных сеансаў...", @"settings.sessions.loading",
                        @"Сеансы недаступныя: %@", @"settings.sessions.failed",
                        @"Спіс сеансаў састарэў. Абнаўляю...", @"settings.sessions.stale",
                        @"Актыўных прылад: %lu", @"settings.sessions.count",
                        @"Аўтазавяршэнне неактыўных сеансаў: %ld дз.", @"settings.sessions.ttl",
                        @"Апошняя актыўнасць: %@", @"settings.sessions.lastActive",
                        @"Невядомая прылада", @"settings.sessions.unknownDevice",
                        @"невядомая памылка", @"settings.sessions.unknownError",
                        @"Бягучая прылада", @"settings.sessions.current",
                        @"Няма іншых актыўных сеансаў", @"settings.sessions.empty",
                        @"Выберыце прыладу для завяршэння", @"settings.sessions.selectDevice",
                        @"Завяршыць", @"settings.sessions.terminate",
                        @"Завяршыць сеанс", @"settings.sessions.terminate.title",
                        @"Завяршыць сеанс на прыладзе «%@»?", @"settings.sessions.terminate.message",
                        @"Завяршэнне сеанса...", @"settings.sessions.terminating",
                        @"Сеанс завершаны.", @"settings.sessions.terminate.done",
                        @"Не атрымалася завяршыць сеанс: %@", @"settings.sessions.terminate.failed",
                        @"Агульныя медыя і файлы", @"media.center.titleCard",
                        @"Новыя элементы зверху. Звычайны клік адкрывае прадпрагляд; пераход да паведамлення даступны праз правую кнопку.", @"media.center.hint",
                        @"Выберыце чат, каб паглядзець медыя.", @"media.center.chooseChat",
                        @"Загрузка медыя...", @"media.center.loading",
                        @"Спачатку адкрыйце чат.", @"media.center.openChatFirst",
                        @"Медыя не знойдзены.", @"media.center.empty",
                        @"%lu элемент(аў), лакальны кэш %@. Пракруціце ўніз, каб загрузіць яшчэ.", @"media.center.loadedStatus",
                        @"%lu элемент(аў), лакальны кэш %@. Усе знойдзеныя элементы загружаны.", @"media.center.loadedStatus.done",
                        @"Загрузка яшчэ...", @"media.center.loadingMore",
                        @"Пошук медыя не атрымаўся: %@", @"media.center.failed",
                        @"Медыя", @"media.center.tab.media",
                        @"Файлы", @"media.center.tab.files",
                        @"Спасылкі", @"media.center.tab.links",
                        @"Музыка", @"media.center.tab.music",
                        @"Голас", @"media.center.tab.voice",
                        @"GIF", @"media.center.tab.gif",
                        @"Апытанні", @"media.center.tab.polls",
                        @"Групы", @"media.center.tab.groups",
                        @"%lu агульных груп.", @"media.center.groups.loadedStatus",
                        @"Агульныя групы не знойдзены.", @"media.center.groups.empty",
                        @"Агульныя групы даступныя толькі для асабістых чатаў.", @"media.center.groups.privateOnly",
                        @"Без назвы", @"media.center.group.untitled",
                        @"У гэтага элемента пакуль няма id файла.", @"media.center.noFileID",
                        @"Спампоўваем медыя...", @"media.center.downloading",
                        @"Спампавана %@", @"media.center.downloaded",
                        @"Памылка спампоўкі: %@", @"media.center.downloadFailed",
                        @"Спачатку спампуйце гэты элемент.", @"media.center.downloadBeforeOpen",
                        @"Не атрымалася адкрыць файл сістэмнай праграмай.", @"media.center.openFailed",
                        @"Прадпрагляд", @"media.center.preview",
                        @"Адкрыць файл", @"media.center.open",
                        @"Спампаваць", @"media.center.download",
                        @"Перайсці да файла", @"media.center.goToFile",
                        @"Выдаліць лакальную копію", @"media.center.deleteLocal",
                        @"Для гэтага элемента няма прадпрагляду. Выкарыстайце правую кнопку, каб спампаваць або адкрыць файл.", @"media.center.previewUnavailable",
                        @"Выкарыстанне памяці", @"storage.open",
                        @"Выкарыстанне памяці", @"storage.title",
                        @"Загрузка...", @"storage.loading",
                        @"Усяго: %@", @"storage.total",
                        @"Файлы", @"storage.files",
                        @"База TDLib", @"storage.database",
                        @"Моўныя пакеты", @"storage.language",
                        @"Логі", @"storage.logs",
                        @"Медыя і дакументы застануцца ў воблаку Telegram, пры неабходнасці іх можна спампаваць зноў.", @"storage.safeHint",
                        @"Ачысціць кэш", @"storage.clear",
                        @"Абнавіць", @"storage.refresh",
                        @"Статыстыка недаступная", @"storage.unavailable",
                        @"Ачышчаем кэш...", @"storage.clearing",
                        @"Не атрымалася ачысціць кэш", @"storage.clearFailed",
                        @"Кэш ачышчаны. Абноўлены памер паказаны вышэй.", @"storage.clearDone",
                        @"Ачысціць кэш Telegraphica?", @"storage.confirm.title",
                        @"Спампаваныя медыя будуць выдалены з гэтага Mac, але застануцца ў Telegram. Аўтарызацыя і паведамленні не будуць закрануты.", @"storage.confirm.message",
                        @"Выдаліць лакальныя даныя", @"settings.localData.delete",
                        @"Выдаліць лакальныя даныя Telegraphica?", @"settings.localData.confirm.title",
                        @"Будзе выдалена лакальная база TDLib, кэш, прэв'ю, чарнавікі, дыягнастычныя логі і лакальны ключ базы на гэтым Mac. Даныя ў воблаку Telegram і файлы ў Downloads не будуць закрануты. Пасля гэтага трэба будзе ўвайсці зноў.", @"settings.localData.confirm.message",
                        @"Лакальныя даныя выдалены. Telegraphica вернецца да экрана ўваходу.", @"settings.localData.done",
                        @"Лакальныя даныя выдалены, але частка ачысткі не завяршылася: %@", @"settings.localData.partial",
                        @"Выдаленне лакальных даных...", @"settings.localData.busy",
                        @"Закрыць", @"close",
                        @"Новае паведамленне", @"notification.hiddenPreview",
                        @"Пачаць запіс голасу?", @"voice.permission.title",
                        @"Telegraphica зможа выкарыстоўваць мікрафон для запісу галасавых паведамленняў. Запіс пачынаецца толькі пасля націску кнопкі голасу.", @"voice.permission.message",
                        @"Запісваецца...", @"voice.recording",
                        @"Націсніце кнопку голасу яшчэ раз, каб спыніць запіс", @"voice.stopHint",
                        @"Адпраўка...", @"sending",
                        @"Адзначыць прачытаным", @"chat.markRead",
                        @"Прачытаць усе чаты", @"chat.readAll",
                        @"Замацаваць дыялог", @"chat.pin",
                        @"Адмацаваць дыялог", @"chat.unpin",
                        @"Уключыць лакальныя апавяшчэнні", @"chat.notifications.enable",
                        @"Адключыць апавяшчэнні", @"chat.notifications.mute",
                        @"На 1 гадзіну", @"chat.notifications.hour",
                        @"На 1 дзень", @"chat.notifications.day",
                        @"Назаўсёды", @"chat.notifications.forever",
                        @"Замацаваць паведамленне", @"message.pin",
                        @"Адмацаваць паведамленне", @"message.unpin",
                        @"Адказаць", @"message.reply",
                        @"Пераслаць...", @"message.forward",
                        @"Пераслаць у Выбранае", @"message.forward.saved",
                        @"Адкрыць каментары", @"message.comments.open",
                        @"Пракаментаваць", @"message.comments.add",
                        @"%ld каментар", @"message.comments.count.one",
                        @"%ld каментароў", @"message.comments.count.many",
                        @"каментары", @"message.comments.threadSuffix",
                        @"Каментары", @"message.comments.threadTitle",
                        @"Хто прачытаў", @"message.whoRead",
                        @"Хто прачытаў гэта паведамленне", @"message.viewers.title",
                        @"Загружаем чытачоў...", @"message.viewers.loading",
                        @"Чытачы недаступныя для гэтага паведамлення.", @"message.viewers.unavailable",
                        @"Ніхто яшчэ не прачытаў", @"message.viewers.empty",
                        @"Уваход яшчэ не гатовы", @"message.viewers.signInUnavailable",
                        @"Невядома", @"message.viewers.unknown",
                        @"Няма даных", @"message.viewers.noData",
                        @"Яшчэ рэакцыі", @"message.reactions.more",
                        @"Скапіяваць тэкст", @"message.copyText",
                        @"Скапіяваць неадпраўлены тэкст", @"message.copyUnsentText",
                        @"Паўтарыць адпраўку", @"message.retrySend",
                        @"Адпраўка не атрымалася", @"message.sendFailed",
                        @"Паўтарыць адпраўку?", @"message.retry.confirm.title",
                        @"Паведамленне магло быць адпраўлена, але Telegraphica не атрымала пацвярджэнне. Паўтор можа стварыць дубль.", @"message.retry.confirm.message",
                        @"Пацверджана частак: %lu з %lu. Паўтор можа стварыць дублі ўжо адпраўленых частак.", @"message.retry.confirm.partial",
                        @"Паўтараем адпраўку...", @"message.retry.sending",
                        @"Паведамленне адпраўлена", @"message.retry.sent",
                        @"Паўтор не атрымаўся", @"message.retry.failed",
                        @"Спампаваць медыя", @"message.downloadMedia",
                        @"Спампаваць дакумент", @"message.downloadDocument",
                        @"Спампаваць", @"message.download.action",
                        @"Рэдагаваць", @"message.edit",
                        @"Рэдагаваць паведамленне", @"message.edit.title",
                        @"Выпраўце тэкст і захавайце змены.", @"message.edit.hint",
                        @"Захаваць", @"message.edit.save",
                        @"Выдаліць паведамленне", @"message.delete",
                        @"Выдаліць паведамленне?", @"message.delete.title",
                        @"Гэта дзеянне нельга адмяніць.", @"message.delete.hint",
                        @"Выдаліць", @"message.delete.action",
                        @"Выдаліць у мяне", @"message.delete.self",
                        @"Выдаліць ва ўсіх", @"message.delete.everyone",
                        @"Галасаваць", @"message.poll.vote",
                        @"Стварыць апытанне...", @"poll.create.menu",
                        @"Стварыць апытанне", @"poll.create.title",
                        @"Увядзіце пытанне і варыянты адказу. Кожны варыянт павінен быць у асобным радку.", @"poll.create.hint",
                        @"Пытанне", @"poll.create.question",
                        @"Варыянты", @"poll.create.options",
                        @"Некалькі адказаў", @"poll.create.multiple",
                        @"Ананімнае апытанне", @"poll.create.anonymous",
                        @"Адпраўляем апытанне...", @"poll.create.sending",
                        @"Апытанне адпраўлена", @"poll.create.sent",
                        @"Не ўдалося адправіць апытанне", @"poll.create.failed",
                        @"Не ўдалося стварыць апытанне", @"poll.create.error.title",
                        @"Увядзіце пытанне.", @"poll.create.error.question",
                        @"Дадайце мінімум два розныя варыянты.", @"poll.create.error.options",
                        @"Варыянт %lu", @"message.poll.optionFallback",
                        @"Няма варыянтаў", @"message.poll.noOptions",
                        @"Адпраўляем голас...", @"message.poll.sending",
                        @"Голас улічаны", @"message.poll.sent",
                        @"Не ўдалося прагаласаваць", @"message.poll.failed",
                        @"Пацвердзіць выбар", @"message.poll.submit",
                        @"Выберыце варыянты і пацвердзіце", @"message.poll.multipleHint",
                        @"закрыта", @"message.poll.closed",
                        @"quiz", @"message.poll.quiz",
                        @"%ld голас", @"message.poll.votes.one",
                        @"%ld галасоў", @"message.poll.votes.many",
                        @"Пошук чатаў", @"search.chats.title",
                        @"Чат, група, чалавек", @"search.chats.placeholder",
                        @"Нядаўнія чаты з'явяцца тут", @"search.chats.emptyRecent",
                        @"Чаты не знойдзены", @"search.chats.empty",
                        @"Нядаўнія чаты. Увядзіце запыт, каб знайсці чат, групу ці чалавека.", @"search.chats.recent",
                        @"Загружаем нядаўнія чаты...", @"search.chats.loadingRecent",
                        @"Шукаем чаты...", @"search.chats.searching",
                        @"Загружана супадзенняў: %lu. Шукаем далей...", @"search.chats.loadedSearching",
                        @"Знойдзена чатаў: %lu", @"search.chats.found",
                        @"Пошук не атрымаўся: %@", @"search.chats.failed",
                        @"Загружаных чатаў пакуль няма", @"search.chats.noLoaded",
                        @"Адкрыць чат", @"search.chats.openHint",
                        @"Чат", @"search.chats.fallbackChat",
                        @"Выбранае", @"savedMessages",
                        @"Новая версія Telegraphica", @"update.title",
                        @"Адкрыць старонку загрузкі", @"update.open",
                        @"Не зараз", @"update.later",
                        @"Спампаваць абнаўленне", @"update.download",
                        @"Абнаўленняў няма", @"update.none",
                        @"Усталявана версія %@", @"update.noneMessage",
                        @"Даступная версія %@. Спампаваць усталёўшчык абнаўлення?", @"update.availableMessage",
                        @"Не атрымалася праверыць абнаўленні: %@", @"update.failed",
                        @"Абнаўленне спампавана", @"update.downloaded.title",
                        @"Файл захаваны: %@", @"update.downloaded.message",
                        @"Адкрыць усталёўшчык", @"update.downloaded.open",
                        @"Не атрымалася спампаваць абнаўленне", @"update.download.failed.title",
                        @"Памылка загрузкі: %@. Можна адкрыць старонку рэлізу і спампаваць файл уручную.", @"update.download.failed.message",
                        @"Профіль", @"profile.title",
                        @"Профіль", @"profile.fallback",
                        @"Пра сябе", @"profile.about",
                        @"Акаўнт", @"profile.account",
                        @"Імя карыстальніка", @"profile.username",
                        @"Тэлефон", @"profile.phone",
                        @"Telegram ID", @"profile.id",
                        @"Выйсці", @"profile.logout",
                        @"Абнавіць профіль", @"profile.refresh",
                        @"Увайсці", @"login.title",
                        @"Увядзіце нумар тэлефона, звязаны з акаўнтам Telegram, разам з кодам краіны.", @"login.phone.hint",
                        @"Нумар тэлефона", @"login.phone.label",
                        @"Увядзіце код", @"login.code.title",
                        @"Код прыйдзе ў Telegram. Увядзіце яго тут, каб працягнуць уваход.", @"login.code.hint",
                        @"Код уваходу", @"login.code.label",
                        @"Двухэтапная аўтэнтыфікацыя", @"login.password.title",
                        @"Увядзіце воблачны пароль Telegram. Telegraphica не запісвае яго ў логі.", @"login.password.hint",
                        @"Пароль", @"login.password.label",
                        @"Адправіць", @"login.send",
                        @"Адпраўка...", @"login.sending",
                        @"Логі", @"login.logs",
                        @"Статус", @"login.status",
                        @"Падключэнне", @"login.connecting.title",
                        @"Telegraphica ўсталёўвае бяспечнае злучэнне з Telegram. Гэта можа заняць некалькі секунд.", @"login.connecting.hint",
                        @"Завяршаем папярэднюю сесію і рыхтуем новы ўваход.", @"login.recovering.hint",
                        @"Паўтарыць", @"login.retry",
                        @"Не атрымалася падрыхтаваць уваход", @"login.config.title",
                        @"У гэтай зборцы адсутнічае ўнутраная канфігурацыя падключэння. Падрабязнасці даступныя ў логах.", @"login.config.missing",
                        @"Праверце нумар тэлефона і паспрабуйце зноў.", @"login.error.phone",
                        @"Гэты код не прыняты. Праверце Telegram і паспрабуйце зноў.", @"login.error.code",
                        @"Гэты пароль не прыняты. Паспрабуйце зноў.", @"login.error.password",
                        @"Не атрымалася ўвайсці. Паспрабуйце зноў.", @"login.error.general",
                        @"Увядзіце нумар тэлефона, каб працягнуць.", @"login.empty.phone",
                        @"Увядзіце код уваходу з Telegram.", @"login.empty.code",
                        @"Увядзіце пароль двухэтапнай аўтэнтыфікацыі.", @"login.empty.password",
                        @"Няма злучэння. Падрабязнасці даступныя ў логах.", @"login.connection.unavailable",
                        @"Пра Telegraphica", @"about.title",
                        @"Версія %@ (%@)", @"about.version",
                        @"Усе правы абаронены.", @"about.rights",
                        @"Для Intel Mac з OS X 10.8–macOS 10.13.\nАсноўная распрацоўка і праверка — на OS X 10.9: зробім скевамарфічныя сістэмы зноў вялікімі.\nНовыя macOS і Apple Silicon — без гарантый; агульная падтрымка Intel-праграм Rosetta заканчваецца пасля macOS 27.", @"about.compatibility",
                        @"Аўтар: Yura Menschikov", @"about.author",
                        @"Праект на GitHub", @"about.project",
                        @"Канал Telegraphica у Telegram", @"about.channel",
                        @"Адкрыць канал Telegraphica", @"about.channel.open.title",
                        @"Дзе адкрыць канал @macos_telegraphica?", @"about.channel.open.message",
                        @"У Telegraphica", @"about.channel.open.app",
                        @"У браўзеры", @"about.channel.open.browser",
                        @"Скасаваць", @"common.cancel",
                        @"Адкрываю канал Telegraphica...", @"about.channel.opening",
                        @"Канал Telegraphica адкрыты.", @"about.channel.opened",
                        @"Не ўдалося адкрыць канал у Telegraphica.", @"about.channel.open.failed",
                        @"Можна адкрыць канал у браўзеры.", @"about.channel.open.browserFallback",
                        nil];
    NSDictionary *en = [NSDictionary dictionaryWithObjectsAndKeys:
                        @"Chats", @"chats",
                        @"Back", @"back",
                        @"Workshop", @"workshop.title",
                        @"Open Workshop", @"workshop.openTooltip",
                        @"Available", @"workshop.available",
                        @"Installed", @"workshop.installed",
                        @"Updates", @"workshop.updates",
                        @"Refresh catalog", @"workshop.refreshCatalog",
                        @"Refreshing catalog...", @"workshop.refreshing",
                        @"Games", @"workshop.games",
                        @"Version", @"workshop.version",
                        @"Install", @"workshop.install",
                        @"Installing...", @"workshop.installing",
                        @"Game installed", @"workshop.installComplete",
                        @"Open", @"workshop.open",
                        @"Update", @"workshop.update",
                        @"Remove", @"workshop.remove",
                        @"Retry", @"workshop.retry",
                        @"Installed version:", @"workshop.installedVersion",
                        @"Not installed", @"workshop.notInstalled",
                        @"There is nothing in this section yet.", @"workshop.empty",
                        @"The catalog is temporarily unavailable. Installed games will continue to work offline.", @"workshop.catalogUnavailable",
                        @"Catalog unavailable; showing local data.", @"workshop.offlineHint",
                        @"Modules: %lu", @"workshop.itemsCount",
                        @"The action could not be completed.", @"workshop.unknownError",
                        @"Remove game?", @"workshop.removeConfirmTitle",
                        @"You can keep progress or remove the game with all saved data. An open game will close, and its files will be removed after Telegraphica restarts.", @"workshop.removeConfirmMessage",
                        @"Remove and keep progress", @"workshop.removeKeepData",
                        @"Remove with progress", @"workshop.removeWithData",
                        @"The damaged save was quarantined for diagnostics. A new game was started.", @"game.save_recovered",
                        @"Computer", @"game.computer",
                        @"Two players", @"game.twoPlayers",
                        @"Easy", @"game.easy",
                        @"Medium", @"game.medium",
                        @"Hard", @"game.hard",
                        @"New round", @"game.newRound",
                        @"Draw", @"game.draw",
                        @"%@ wins", @"game.winner",
                        @"%@ to move", @"game.turn",
                        @"Draws", @"game.draws",
                        @"Restart", @"game.restart",
                        @"Time", @"game.time",
                        @"You won", @"game.won",
                        @"Game over", @"game.lost",
                        @"New game", @"game.newGame",
                        @"Pause", @"game.pause",
                        @"Resume", @"game.resume",
                        @"Paused", @"game.paused",
                        @"Score", @"game.score",
                        @"Lives", @"game.lives",
                        @"Undo", @"game.undo",
                        @"Wins", @"game.wins",
                        @"Use arrow keys or WASD", @"pacman.hint",
                        @"Pellets", @"pacman.pellets",
                        @"Tic-Tac-Toe", @"tictactoe.title",
                        @"Minesweeper", @"minesweeper.title",
                        @"Choose a cell", @"minesweeper.ready",
                        @"Clear the field", @"minesweeper.playing",
                        @"Mines", @"minesweeper.mines",
                        @"Checkers", @"checkers.title",
                        @"New game", @"checkers.new_game",
                        @"Red wins", @"checkers.red_wins",
                        @"Black wins", @"checkers.black_wins",
                        @"Continue capturing", @"checkers.continue_capture",
                        @"Red to move", @"checkers.red_turn",
                        @"Black to move", @"checkers.black_turn",
                        @"Red", @"checkers.red",
                        @"Black", @"checkers.black",
                        @"Solitaire", @"solitaire.title",
                        @"New deal", @"solitaire.new_deal",
                        @"Drag cards or double-click to move home.", @"solitaire.hint",
                        @"Chats are closed", @"closedChats.title",
                        @"Choose a recent private chat to continue the conversation.", @"closedChats.hint",
                        @"All chats", @"drawer.all",
                        @"All chats", @"drawer.all.tooltip",
                        @"Pinned message", @"pinned.title",
                        @"Profile", @"profile",
                        @"Settings", @"settings",
                        @"Message", @"message",
                        @"Message", @"message.placeholder",
                        @"You", @"message.you",
                        @"Reply", @"reply",
                        @"Reply to %@", @"reply.to",
                        @"Reply to yourself", @"reply.toSelf",
                        @"Forwarded from %@", @"forwarded.from",
                        @"Original message", @"message.original",
                        @"Image", @"media.image",
                        @"Video", @"media.video",
                        @"GIF", @"media.gif",
                        @"Document", @"media.document",
                        @"Media", @"media.media",
                        @"Media center", @"media.center.title",
                        @"Chat info", @"media.center.windowTitle",
                        @"Sticker", @"media.sticker",
                        @"Voice message", @"media.voice",
                        @"Video note", @"media.videoNote",
                        @"Service message", @"media.service",
                        @"Text", @"media.text",
                        @"Attach photo", @"attach.photo",
                        @"Attach file...", @"attach.file",
                        @"Stickers", @"stickers",
                        @"Recent stickers", @"stickers.recent",
                        @"Recent", @"stickers.recent.tab",
                        @"Recent", @"stickers.recent.short",
                        @"Favorites", @"stickers.favorites.tab",
                        @"Fav", @"stickers.favorites.short",
                        @"Emoji", @"stickers.search.placeholder",
                        @"Remove set", @"stickers.removeSet",
                        @"Remove", @"stickers.removeSet.short",
                        @"Voice", @"voice",
                        @"Send", @"send",
                        @"Cancel", @"cancel",
                        @"OK", @"ok",
                        @"Add a caption...", @"caption.placeholder",
                        @"Show message notifications", @"settings.notifications",
                        @"Play notification sound", @"settings.sound",
                        @"Show unread badge in Dock", @"settings.badge",
                        @"Show message preview", @"settings.preview",
                        @"Notify while Telegraphica is active", @"settings.whenActive",
                        @"Hide side drawer", @"settings.drawer",
                        @"Show when someone is typing", @"settings.typing",
                        @"Category", @"settings.theme.category",
                        @"Light themes", @"settings.theme.category.light",
                        @"Dark themes", @"settings.theme.category.dark",
                        @"Retro", @"settings.theme.category.oldSchool",
                        @"Experimental", @"settings.theme.category.experimental",
                        @"Visual Worlds", @"settings.theme.category.visualWorlds",
                        @"Theme", @"settings.theme",
                        @"Appearance", @"settings.appearance",
                        @"Downloads folder", @"settings.downloads",
                        @"Language", @"settings.language",
                        @"Messages as blocks", @"settings.messages.blocks",
                        @"Text size", @"settings.chatText",
                        @"Small", @"settings.chatText.small",
                        @"Normal", @"settings.chatText.normal",
                        @"Large", @"settings.chatText.large",
                        @"Very large", @"settings.chatText.veryLarge",
                        @"Check for Updates", @"settings.update",
                        @"Diagnostic Logs", @"settings.logs",
                        @"About Telegraphica", @"settings.about",
                        @"Notifications", @"settings.section.notifications",
                        @"General", @"settings.section.drawer",
                        @"Resources", @"settings.section.resources",
                        @"Active Sessions", @"settings.section.sessions",
                        @"Interface", @"settings.section.interface",
                        @"Files", @"settings.section.files",
                        @"Help", @"settings.section.help",
                        @"Choose where downloaded files will be saved", @"settings.downloads.help",
                        @"Devices currently signed in to this account", @"settings.sessions.help",
                        @"Economy mode", @"settings.resources.economy",
                        @"Auto-download photos", @"settings.resources.photos",
                        @"Auto-download videos", @"settings.resources.videos",
                        @"Auto-download documents", @"settings.resources.documents",
                        @"Autoplay animated stickers", @"settings.resources.autoplay",
                        @"Stop animations while the window is inactive", @"settings.resources.stopInactive",
                        @"Maximum auto-download size", @"settings.resources.maxDownload",
                        @"Active animations", @"settings.resources.maxAnimations",
                        @"Media cache limit", @"settings.resources.cacheLimit",
                        @"Economy mode reduces auto-downloads, disables extra animations, and keeps cache smaller. Individual values remain editable.", @"settings.resources.hint",
                        @"Open Active Sessions", @"settings.sessions.open",
                        @"Refresh", @"settings.sessions.refresh",
                        @"Loading active sessions...", @"settings.sessions.loading",
                        @"Sessions are unavailable: %@", @"settings.sessions.failed",
                        @"Session list is stale. Refreshing...", @"settings.sessions.stale",
                        @"Active devices: %lu", @"settings.sessions.count",
                        @"Inactive sessions expire after %ld days", @"settings.sessions.ttl",
                        @"Last active: %@", @"settings.sessions.lastActive",
                        @"Unknown device", @"settings.sessions.unknownDevice",
                        @"unknown error", @"settings.sessions.unknownError",
                        @"This device", @"settings.sessions.current",
                        @"No other active sessions", @"settings.sessions.empty",
                        @"Choose a device to terminate", @"settings.sessions.selectDevice",
                        @"Terminate", @"settings.sessions.terminate",
                        @"Terminate Session", @"settings.sessions.terminate.title",
                        @"Terminate the session on “%@”?", @"settings.sessions.terminate.message",
                        @"Terminating session...", @"settings.sessions.terminating",
                        @"Session terminated.", @"settings.sessions.terminate.done",
                        @"Could not terminate session: %@", @"settings.sessions.terminate.failed",
                        @"Shared media and files", @"media.center.titleCard",
                        @"Newest items are shown first. Click previews items; right-click to jump to the message.", @"media.center.hint",
                        @"Choose a chat to view media.", @"media.center.chooseChat",
                        @"Loading media...", @"media.center.loading",
                        @"Open a chat first.", @"media.center.openChatFirst",
                        @"No media found.", @"media.center.empty",
                        @"%lu item(s), local cache %@. Scroll down to load more.", @"media.center.loadedStatus",
                        @"%lu item(s), local cache %@. All found items are loaded.", @"media.center.loadedStatus.done",
                        @"Loading more...", @"media.center.loadingMore",
                        @"Media search failed: %@", @"media.center.failed",
                        @"Media", @"media.center.tab.media",
                        @"Files", @"media.center.tab.files",
                        @"Links", @"media.center.tab.links",
                        @"Music", @"media.center.tab.music",
                        @"Voice", @"media.center.tab.voice",
                        @"GIF", @"media.center.tab.gif",
                        @"Polls", @"media.center.tab.polls",
                        @"Groups", @"media.center.tab.groups",
                        @"%lu common group(s).", @"media.center.groups.loadedStatus",
                        @"No common groups found.", @"media.center.groups.empty",
                        @"Common groups are available only for private chats.", @"media.center.groups.privateOnly",
                        @"Untitled", @"media.center.group.untitled",
                        @"This item has no downloadable file id yet.", @"media.center.noFileID",
                        @"Downloading media...", @"media.center.downloading",
                        @"Downloaded %@", @"media.center.downloaded",
                        @"Download failed: %@", @"media.center.downloadFailed",
                        @"Download this item before opening it.", @"media.center.downloadBeforeOpen",
                        @"Could not open this file with a system app.", @"media.center.openFailed",
                        @"Preview", @"media.center.preview",
                        @"Open file", @"media.center.open",
                        @"Download", @"media.center.download",
                        @"Go to file", @"media.center.goToFile",
                        @"Delete local copy", @"media.center.deleteLocal",
                        @"No preview is available for this item. Right-click to download or open the file.", @"media.center.previewUnavailable",
                        @"Storage Usage", @"storage.open",
                        @"Storage Usage", @"storage.title",
                        @"Loading...", @"storage.loading",
                        @"Total: %@", @"storage.total",
                        @"Files", @"storage.files",
                        @"TDLib database", @"storage.database",
                        @"Language packs", @"storage.language",
                        @"Logs", @"storage.logs",
                        @"Media and documents remain in Telegram cloud and can be downloaded again when needed.", @"storage.safeHint",
                        @"Clear Cache", @"storage.clear",
                        @"Refresh", @"storage.refresh",
                        @"Storage statistics unavailable", @"storage.unavailable",
                        @"Clearing cache...", @"storage.clearing",
                        @"Could not clear cache", @"storage.clearFailed",
                        @"Cache cleared. Updated storage usage is shown above.", @"storage.clearDone",
                        @"Clear Telegraphica cache?", @"storage.confirm.title",
                        @"Downloaded media will be removed from this Mac, but will remain in Telegram. Authorization and messages will not be touched.", @"storage.confirm.message",
                        @"Delete Local Data", @"settings.localData.delete",
                        @"Delete Telegraphica local data?", @"settings.localData.confirm.title",
                        @"This removes the local TDLib database, cache, previews, drafts, diagnostic logs, and local database key from this Mac. Telegram cloud data and files in Downloads are not touched. You will need to sign in again.", @"settings.localData.confirm.message",
                        @"Local data was deleted. Telegraphica will return to the sign-in screen.", @"settings.localData.done",
                        @"Local data was deleted, but part of cleanup did not finish: %@", @"settings.localData.partial",
                        @"Deleting local data...", @"settings.localData.busy",
                        @"Close", @"close",
                        @"New message", @"notification.hiddenPreview",
                        @"Start voice recording?", @"voice.permission.title",
                        @"Telegraphica can use the microphone to record voice messages. Recording starts only after you press the voice button.", @"voice.permission.message",
                        @"Recording...", @"voice.recording",
                        @"Press the voice button again to stop recording", @"voice.stopHint",
                        @"Sending...", @"sending",
                        @"Mark as read", @"chat.markRead",
                        @"Read all chats", @"chat.readAll",
                        @"Pin chat", @"chat.pin",
                        @"Unpin chat", @"chat.unpin",
                        @"Enable local notifications", @"chat.notifications.enable",
                        @"Mute notifications", @"chat.notifications.mute",
                        @"For 1 hour", @"chat.notifications.hour",
                        @"For 1 day", @"chat.notifications.day",
                        @"Forever", @"chat.notifications.forever",
                        @"Pin message", @"message.pin",
                        @"Unpin message", @"message.unpin",
                        @"Reply", @"message.reply",
                        @"Forward...", @"message.forward",
                        @"Forward to Saved Messages", @"message.forward.saved",
                        @"Open comments", @"message.comments.open",
                        @"Comment", @"message.comments.add",
                        @"%ld comment", @"message.comments.count.one",
                        @"%ld comments", @"message.comments.count.many",
                        @"comments", @"message.comments.threadSuffix",
                        @"Comments", @"message.comments.threadTitle",
                        @"Who read", @"message.whoRead",
                        @"Who read this message", @"message.viewers.title",
                        @"Loading readers...", @"message.viewers.loading",
                        @"Readers are unavailable for this message.", @"message.viewers.unavailable",
                        @"Nobody has read it yet", @"message.viewers.empty",
                        @"Sign in is not ready", @"message.viewers.signInUnavailable",
                        @"Unknown", @"message.viewers.unknown",
                        @"No data", @"message.viewers.noData",
                        @"More reactions", @"message.reactions.more",
                        @"Copy text", @"message.copyText",
                        @"Copy unsent text", @"message.copyUnsentText",
                        @"Retry send", @"message.retrySend",
                        @"Send failed", @"message.sendFailed",
                        @"Retry sending?", @"message.retry.confirm.title",
                        @"This message may already have been sent, but Telegraphica did not receive confirmation. Retrying can create a duplicate.", @"message.retry.confirm.message",
                        @"Confirmed parts: %lu of %lu. Retrying can duplicate the parts that were already sent.", @"message.retry.confirm.partial",
                        @"Retrying send...", @"message.retry.sending",
                        @"Message sent", @"message.retry.sent",
                        @"Retry failed", @"message.retry.failed",
                        @"Download media", @"message.downloadMedia",
                        @"Download document", @"message.downloadDocument",
                        @"Download", @"message.download.action",
                        @"Edit", @"message.edit",
                        @"Edit message", @"message.edit.title",
                        @"Update the text and save your changes.", @"message.edit.hint",
                        @"Save", @"message.edit.save",
                        @"Delete message", @"message.delete",
                        @"Delete this message?", @"message.delete.title",
                        @"This action cannot be undone.", @"message.delete.hint",
                        @"Delete", @"message.delete.action",
                        @"Delete for me", @"message.delete.self",
                        @"Delete for everyone", @"message.delete.everyone",
                        @"Vote", @"message.poll.vote",
                        @"Create poll...", @"poll.create.menu",
                        @"Create poll", @"poll.create.title",
                        @"Enter a question and answer options. Put each option on its own line.", @"poll.create.hint",
                        @"Question", @"poll.create.question",
                        @"Options", @"poll.create.options",
                        @"Multiple answers", @"poll.create.multiple",
                        @"Anonymous poll", @"poll.create.anonymous",
                        @"Sending poll...", @"poll.create.sending",
                        @"Poll sent", @"poll.create.sent",
                        @"Could not send poll", @"poll.create.failed",
                        @"Could not create poll", @"poll.create.error.title",
                        @"Enter a question.", @"poll.create.error.question",
                        @"Add at least two different options.", @"poll.create.error.options",
                        @"Option %lu", @"message.poll.optionFallback",
                        @"No options", @"message.poll.noOptions",
                        @"Sending vote...", @"message.poll.sending",
                        @"Vote sent", @"message.poll.sent",
                        @"Could not vote", @"message.poll.failed",
                        @"Submit vote", @"message.poll.submit",
                        @"Choose options, then submit", @"message.poll.multipleHint",
                        @"closed", @"message.poll.closed",
                        @"quiz", @"message.poll.quiz",
                        @"%ld vote", @"message.poll.votes.one",
                        @"%ld votes", @"message.poll.votes.many",
                        @"Search chats", @"search.chats.title",
                        @"Chat, group, person", @"search.chats.placeholder",
                        @"Recent chats will appear here", @"search.chats.emptyRecent",
                        @"No chats found", @"search.chats.empty",
                        @"Recent chats. Type to filter by chat, group, or person.", @"search.chats.recent",
                        @"Loading recent chats...", @"search.chats.loadingRecent",
                        @"Searching chats...", @"search.chats.searching",
                        @"Loaded matches: %lu. Searching more...", @"search.chats.loadedSearching",
                        @"Found chats: %lu", @"search.chats.found",
                        @"Search failed: %@", @"search.chats.failed",
                        @"No loaded chats yet", @"search.chats.noLoaded",
                        @"Open chat", @"search.chats.openHint",
                        @"Chat", @"search.chats.fallbackChat",
                        @"Saved Messages", @"savedMessages",
                        @"New Telegraphica Version", @"update.title",
                        @"Open Download Page", @"update.open",
                        @"Not Now", @"update.later",
                        @"Download Update", @"update.download",
                        @"No Updates", @"update.none",
                        @"Version %@ is installed.", @"update.noneMessage",
                        @"Version %@ is available. Download the update installer?", @"update.availableMessage",
                        @"Could not check for updates: %@", @"update.failed",
                        @"Update Downloaded", @"update.downloaded.title",
                        @"Saved to: %@", @"update.downloaded.message",
                        @"Open Installer", @"update.downloaded.open",
                        @"Could Not Download Update", @"update.download.failed.title",
                        @"Download failed: %@. You can open the release page and download the file manually.", @"update.download.failed.message",
                        @"Profile", @"profile.title",
                        @"Profile", @"profile.fallback",
                        @"About", @"profile.about",
                        @"Account", @"profile.account",
                        @"Username", @"profile.username",
                        @"Phone", @"profile.phone",
                        @"Telegram ID", @"profile.id",
                        @"Logout", @"profile.logout",
                        @"Refresh Profile", @"profile.refresh",
                        @"Sign in", @"login.title",
                        @"Enter the phone number connected to your Telegram account, including country code.", @"login.phone.hint",
                        @"Phone number", @"login.phone.label",
                        @"Enter login code", @"login.code.title",
                        @"The code arrives in Telegram. Enter it here to continue sign-in.", @"login.code.hint",
                        @"Login code", @"login.code.label",
                        @"Two-step password", @"login.password.title",
                        @"Enter your Telegram cloud password. Telegraphica does not write it to logs.", @"login.password.hint",
                        @"Password", @"login.password.label",
                        @"Send", @"login.send",
                        @"Sending...", @"login.sending",
                        @"Logs", @"login.logs",
                        @"Status", @"login.status",
                        @"Connecting", @"login.connecting.title",
                        @"Telegraphica is establishing a secure Telegram connection. This can take a few seconds.", @"login.connecting.hint",
                        @"Finishing the previous session and preparing a fresh sign-in.", @"login.recovering.hint",
                        @"Try Again", @"login.retry",
                        @"Sign-in could not be prepared", @"login.config.title",
                        @"This build is missing its internal connection configuration. Details are available in Logs.", @"login.config.missing",
                        @"Check the phone number and try again.", @"login.error.phone",
                        @"That login code was not accepted. Check Telegram and try again.", @"login.error.code",
                        @"That password was not accepted. Try again.", @"login.error.password",
                        @"Sign-in was not accepted. Try again.", @"login.error.general",
                        @"Enter your phone number to continue.", @"login.empty.phone",
                        @"Enter the login code from Telegram.", @"login.empty.code",
                        @"Enter your two-step password.", @"login.empty.password",
                        @"Connection unavailable. Open Logs for details.", @"login.connection.unavailable",
                        @"About Telegraphica", @"about.title",
                        @"Version %@ (%@)", @"about.version",
                        @"All rights reserved.", @"about.rights",
                        @"For Intel Macs running OS X 10.8–macOS 10.13.\nDeveloped and tested mainly on OS X 10.9: making skeuomorphic systems great again.\nNewer macOS and Apple Silicon are not guaranteed; general Rosetta support for Intel apps ends after macOS 27.", @"about.compatibility",
                        @"Author: Yura Menschikov", @"about.author",
                        @"Project on GitHub", @"about.project",
                        @"Telegraphica Telegram channel", @"about.channel",
                        @"Open Telegraphica channel", @"about.channel.open.title",
                        @"Where should @macos_telegraphica be opened?", @"about.channel.open.message",
                        @"In Telegraphica", @"about.channel.open.app",
                        @"In browser", @"about.channel.open.browser",
                        @"Cancel", @"common.cancel",
                        @"Opening Telegraphica channel...", @"about.channel.opening",
                        @"Telegraphica channel opened.", @"about.channel.opened",
                        @"Could not open the channel in Telegraphica.", @"about.channel.open.failed",
                        @"You can open the channel in the browser instead.", @"about.channel.open.browserFallback",
                        nil];
    NSDictionary *dictionary = [language isEqualToString:@"be"] ? be : ([language isEqualToString:@"en"] ? en : ru);
    NSString *value = [dictionary objectForKey:key];
    return value ? value : key;
}
