#import "TGLocalization.h"

static NSString * const TGLanguageDefaultsKey = @"TelegraphicaLanguageCode";

NSString *TGLanguageCode(void) {
    NSString *code = [[NSUserDefaults standardUserDefaults] stringForKey:TGLanguageDefaultsKey];
    if ([code isEqualToString:@"ru"] || [code isEqualToString:@"be"] || [code isEqualToString:@"en"]) {
        return code;
    }
    return @"ru";
}
void TGSetLanguageCode(NSString *code) {
    NSString *validated = ([code isEqualToString:@"ru"] || [code isEqualToString:@"be"] || [code isEqualToString:@"en"]) ? code : @"ru";
    [[NSUserDefaults standardUserDefaults] setObject:validated forKey:TGLanguageDefaultsKey];
    [[NSUserDefaults standardUserDefaults] synchronize];
}

NSString *TGLoc(NSString *key) {
    if (![key isKindOfClass:[NSString class]]) {
        return @"";
    }

    NSString *language = TGLanguageCode();
    NSDictionary *ru = [NSDictionary dictionaryWithObjectsAndKeys:
                        @"Чаты", @"chats",
                        @"Все чаты", @"drawer.all",
                        @"Все чаты", @"drawer.all.tooltip",
                        @"Закреплённое сообщение", @"pinned.title",
                        @"Профиль", @"profile",
                        @"Настройки", @"settings",
                        @"Сообщение", @"message",
                        @"Сообщение", @"message.placeholder",
                        @"Вы", @"message.you",
                        @"Ответ", @"reply",
                        @"Ответ для %@", @"reply.to",
                        @"Ответ себе", @"reply.toSelf",
                        @"Переслано от %@", @"forwarded.from",
                        @"Оригинальное сообщение", @"message.original",
                        @"Изображение", @"media.image",
                        @"Видео", @"media.video",
                        @"GIF", @"media.gif",
                        @"Документ", @"media.document",
                        @"Медиа", @"media.media",
                        @"Стикер", @"media.sticker",
                        @"Голосовое сообщение", @"media.voice",
                        @"Видеосообщение", @"media.videoNote",
                        @"Сервисное сообщение", @"media.service",
                        @"Текст", @"media.text",
                        @"Прикрепить фото", @"attach.photo",
                        @"Стикеры", @"stickers",
                        @"Голос", @"voice",
                        @"Отправить", @"send",
                        @"Отмена", @"cancel",
                        @"Добавить подпись...", @"caption.placeholder",
                        @"Показывать уведомления", @"settings.notifications",
                        @"Звук уведомлений", @"settings.sound",
                        @"Бейдж непрочитанных в Dock", @"settings.badge",
                        @"Показывать текст сообщения", @"settings.preview",
                        @"Уведомлять, когда Telegraphica открыта", @"settings.whenActive",
                        @"Скрыть боковую панель", @"settings.drawer",
                        @"Показывать, когда собеседник печатает", @"settings.typing",
                        @"Категория", @"settings.theme.category",
                        @"Светлые темы", @"settings.theme.category.light",
                        @"Тёмные темы", @"settings.theme.category.dark",
                        @"Retro", @"settings.theme.category.oldSchool",
                        @"Экспериментальные", @"settings.theme.category.experimental",
                        @"Тема", @"settings.theme",
                        @"Оформление", @"settings.appearance",
                        @"Папка загрузок", @"settings.downloads",
                        @"Язык", @"settings.language",
                        @"Сообщения блоками", @"settings.messages.blocks",
                        @"Размер текста", @"settings.chatText",
                        @"Маленький", @"settings.chatText.small",
                        @"Обычный", @"settings.chatText.normal",
                        @"Крупный", @"settings.chatText.large",
                        @"Очень крупный", @"settings.chatText.veryLarge",
                        @"Проверить обновления", @"settings.update",
                        @"Диагностические логи", @"settings.logs",
                        @"О Telegraphica", @"settings.about",
                        @"Уведомления", @"settings.section.notifications",
                        @"Общие", @"settings.section.drawer",
                        @"Ресурсы", @"settings.section.resources",
                        @"Активные сессии", @"settings.section.sessions",
                        @"Интерфейс", @"settings.section.interface",
                        @"Файлы", @"settings.section.files",
                        @"Справка", @"settings.section.help",
                        @"Выберите папку, в которой будут сохраняться загруженные файлы", @"settings.downloads.help",
                        @"Устройства, на которых выполнен вход в этот аккаунт", @"settings.sessions.help",
                        @"Экономичный режим", @"settings.resources.economy",
                        @"Автозагрузка фото", @"settings.resources.photos",
                        @"Автозагрузка видео", @"settings.resources.videos",
                        @"Автозагрузка документов", @"settings.resources.documents",
                        @"Автовоспроизведение анимированных стикеров", @"settings.resources.autoplay",
                        @"Останавливать анимации, когда окно неактивно", @"settings.resources.stopInactive",
                        @"Максимальный размер автозагрузки", @"settings.resources.maxDownload",
                        @"Активных анимаций", @"settings.resources.maxAnimations",
                        @"Лимит медиакэша", @"settings.resources.cacheLimit",
                        @"Экономичный режим снижает автозагрузку, отключает лишние анимации и уменьшает кэш. Отдельные пункты можно менять вручную.", @"settings.resources.hint",
                        @"Открыть активные сессии", @"settings.sessions.open",
                        @"Обновить", @"settings.sessions.refresh",
                        @"Загрузка активных сессий...", @"settings.sessions.loading",
                        @"Сессии недоступны: %@", @"settings.sessions.failed",
                        @"Список сессий устарел. Обновляю...", @"settings.sessions.stale",
                        @"Активных устройств: %lu", @"settings.sessions.count",
                        @"Автозавершение неактивных сессий: %ld дн.", @"settings.sessions.ttl",
                        @"Последняя активность: %@", @"settings.sessions.lastActive",
                        @"Неизвестное устройство", @"settings.sessions.unknownDevice",
                        @"неизвестная ошибка", @"settings.sessions.unknownError",
                        @"Текущее устройство", @"settings.sessions.current",
                        @"Нет других активных сессий", @"settings.sessions.empty",
                        @"Завершить", @"settings.sessions.terminate",
                        @"Завершить сессию", @"settings.sessions.terminate.title",
                        @"Завершить сессию на устройстве «%@»?", @"settings.sessions.terminate.message",
                        @"Завершение сессии...", @"settings.sessions.terminating",
                        @"Сессия завершена.", @"settings.sessions.terminate.done",
                        @"Не удалось завершить сессию: %@", @"settings.sessions.terminate.failed",
                        @"Использование памяти", @"storage.open",
                        @"Использование памяти", @"storage.title",
                        @"Загрузка...", @"storage.loading",
                        @"Всего: %@", @"storage.total",
                        @"Файлы", @"storage.files",
                        @"База TDLib", @"storage.database",
                        @"Языковые пакеты", @"storage.language",
                        @"Логи", @"storage.logs",
                        @"Медиа и документы останутся в облаке Telegram, при необходимости их можно скачать заново.", @"storage.safeHint",
                        @"Очистить кэш", @"storage.clear",
                        @"Обновить", @"storage.refresh",
                        @"Статистика недоступна", @"storage.unavailable",
                        @"Очищаем кэш...", @"storage.clearing",
                        @"Не удалось очистить кэш", @"storage.clearFailed",
                        @"Кэш очищен. Обновлённый размер показан выше.", @"storage.clearDone",
                        @"Очистить кэш Telegraphica?", @"storage.confirm.title",
                        @"Скачанные медиа будут удалены с этого Mac, но останутся в Telegram. Авторизация и сообщения не будут затронуты.", @"storage.confirm.message",
                        @"Удалить локальные данные", @"settings.localData.delete",
                        @"Удалить локальные данные Telegraphica?", @"settings.localData.confirm.title",
                        @"Будут удалены локальная база TDLib, кэш, превью, черновики, диагностические логи и локальный ключ базы на этом Mac. Данные в облаке Telegram и файлы в Downloads не будут затронуты. После этого нужно будет войти заново.", @"settings.localData.confirm.message",
                        @"Локальные данные удалены. Telegraphica вернётся к экрану входа.", @"settings.localData.done",
                        @"Локальные данные удалены, но часть очистки не завершилась: %@", @"settings.localData.partial",
                        @"Удаление локальных данных...", @"settings.localData.busy",
                        @"Закрыть", @"close",
                        @"Новое сообщение", @"notification.hiddenPreview",
                        @"Начать запись голоса?", @"voice.permission.title",
                        @"Telegraphica сможет использовать микрофон для записи голосовых сообщений. Запись начинается только после нажатия кнопки голоса.", @"voice.permission.message",
                        @"Записывается...", @"voice.recording",
                        @"Нажмите кнопку голоса ещё раз, чтобы остановить запись", @"voice.stopHint",
                        @"Отправка...", @"sending",
                        @"Отметить прочитанным", @"chat.markRead",
                        @"Прочитать все чаты", @"chat.readAll",
                        @"Закрепить диалог", @"chat.pin",
                        @"Открепить диалог", @"chat.unpin",
                        @"Включить локальные уведомления", @"chat.notifications.enable",
                        @"Отключить уведомления", @"chat.notifications.mute",
                        @"На 1 час", @"chat.notifications.hour",
                        @"На 1 день", @"chat.notifications.day",
                        @"Навсегда", @"chat.notifications.forever",
                        @"Закрепить сообщение", @"message.pin",
                        @"Открепить сообщение", @"message.unpin",
                        @"Ответить", @"message.reply",
                        @"Переслать...", @"message.forward",
                        @"Переслать в Избранное", @"message.forward.saved",
                        @"Открыть комментарии", @"message.comments.open",
                        @"Прокомментировать", @"message.comments.add",
                        @"%ld комментарий", @"message.comments.count.one",
                        @"%ld комментариев", @"message.comments.count.many",
                        @"комментарии", @"message.comments.threadSuffix",
                        @"Комментарии", @"message.comments.threadTitle",
                        @"Кто прочитал", @"message.whoRead",
                        @"Кто прочитал это сообщение", @"message.viewers.title",
                        @"Загружаем читателей...", @"message.viewers.loading",
                        @"Читатели недоступны для этого сообщения.", @"message.viewers.unavailable",
                        @"Никто ещё не прочитал", @"message.viewers.empty",
                        @"Вход ещё не готов", @"message.viewers.signInUnavailable",
                        @"Неизвестно", @"message.viewers.unknown",
                        @"Нет данных", @"message.viewers.noData",
                        @"Ещё реакции", @"message.reactions.more",
                        @"Копировать текст", @"message.copyText",
                        @"Копировать неотправленный текст", @"message.copyUnsentText",
                        @"Повторить отправку", @"message.retrySend",
                        @"Отправка не удалась", @"message.sendFailed",
                        @"Повторить отправку?", @"message.retry.confirm.title",
                        @"Сообщение могло быть отправлено, но Telegraphica не получила подтверждение. Повтор может создать дубль.", @"message.retry.confirm.message",
                        @"Подтверждено частей: %lu из %lu. Повтор может создать дубли уже отправленных частей.", @"message.retry.confirm.partial",
                        @"Повторяем отправку...", @"message.retry.sending",
                        @"Сообщение отправлено", @"message.retry.sent",
                        @"Повтор не удался", @"message.retry.failed",
                        @"Скачать медиа", @"message.downloadMedia",
                        @"Скачать документ", @"message.downloadDocument",
                        @"Скачать", @"message.download.action",
                        @"Редактировать", @"message.edit",
                        @"Редактировать сообщение", @"message.edit.title",
                        @"Исправьте текст и сохраните изменения.", @"message.edit.hint",
                        @"Сохранить", @"message.edit.save",
                        @"Удалить сообщение", @"message.delete",
                        @"Удалить сообщение?", @"message.delete.title",
                        @"Это действие нельзя отменить.", @"message.delete.hint",
                        @"Удалить у меня", @"message.delete.self",
                        @"Удалить у всех", @"message.delete.everyone",
                        @"Голосовать", @"message.poll.vote",
                        @"Вариант %lu", @"message.poll.optionFallback",
                        @"Вариантов нет", @"message.poll.noOptions",
                        @"Отправляем голос...", @"message.poll.sending",
                        @"Голос учтён", @"message.poll.sent",
                        @"Не удалось проголосовать", @"message.poll.failed",
                        @"%ld голос", @"message.poll.votes.one",
                        @"%ld голосов", @"message.poll.votes.many",
                        @"Поиск чатов", @"search.chats.title",
                        @"Чат, группа, человек", @"search.chats.placeholder",
                        @"Недавние чаты появятся здесь", @"search.chats.emptyRecent",
                        @"Чаты не найдены", @"search.chats.empty",
                        @"Недавние чаты. Введите запрос, чтобы найти чат, группу или человека.", @"search.chats.recent",
                        @"Загружаем недавние чаты...", @"search.chats.loadingRecent",
                        @"Ищем чаты...", @"search.chats.searching",
                        @"Загружено совпадений: %lu. Ищем дальше...", @"search.chats.loadedSearching",
                        @"Найдено чатов: %lu", @"search.chats.found",
                        @"Поиск не удался: %@", @"search.chats.failed",
                        @"Загруженных чатов пока нет", @"search.chats.noLoaded",
                        @"Открыть чат", @"search.chats.openHint",
                        @"Чат", @"search.chats.fallbackChat",
                        @"Избранное", @"savedMessages",
                        @"Новая версия Telegraphica", @"update.title",
                        @"Открыть страницу загрузки", @"update.open",
                        @"Не сейчас", @"update.later",
                        @"Скачать обновление", @"update.download",
                        @"Обновлений нет", @"update.none",
                        @"Установлена версия %@", @"update.noneMessage",
                        @"Доступна версия %@. Скачать установщик обновления?", @"update.availableMessage",
                        @"Не удалось проверить обновления: %@", @"update.failed",
                        @"Обновление скачано", @"update.downloaded.title",
                        @"Файл сохранён: %@", @"update.downloaded.message",
                        @"Открыть установщик", @"update.downloaded.open",
                        @"Не удалось скачать обновление", @"update.download.failed.title",
                        @"Ошибка загрузки: %@. Можно открыть страницу релиза и скачать файл вручную.", @"update.download.failed.message",
                        @"Профиль", @"profile.title",
                        @"Профиль", @"profile.fallback",
                        @"О себе", @"profile.about",
                        @"Аккаунт", @"profile.account",
                        @"Имя пользователя", @"profile.username",
                        @"Телефон", @"profile.phone",
                        @"Telegram ID", @"profile.id",
                        @"Выйти", @"profile.logout",
                        @"Обновить профиль", @"profile.refresh",
                        @"Войти", @"login.title",
                        @"Введите номер телефона, связанный с аккаунтом Telegram, вместе с кодом страны.", @"login.phone.hint",
                        @"Номер телефона", @"login.phone.label",
                        @"Введите код", @"login.code.title",
                        @"Код придёт в Telegram. Введите его здесь, чтобы продолжить вход.", @"login.code.hint",
                        @"Код входа", @"login.code.label",
                        @"Двухэтапная аутентификация", @"login.password.title",
                        @"Введите облачный пароль Telegram. Telegraphica не записывает его в логи.", @"login.password.hint",
                        @"Пароль", @"login.password.label",
                        @"Отправить", @"login.send",
                        @"Отправка...", @"login.sending",
                        @"Логи", @"login.logs",
                        @"Статус", @"login.status",
                        @"Подключение", @"login.connecting.title",
                        @"Telegraphica устанавливает безопасное соединение с Telegram. Это может занять несколько секунд.", @"login.connecting.hint",
                        @"Завершаем предыдущую сессию и готовим новый вход.", @"login.recovering.hint",
                        @"Повторить", @"login.retry",
                        @"Не удалось подготовить вход", @"login.config.title",
                        @"В этой сборке отсутствует внутренняя конфигурация подключения. Подробности доступны в логах.", @"login.config.missing",
                        @"Проверьте номер телефона и попробуйте снова.", @"login.error.phone",
                        @"Этот код не принят. Проверьте Telegram и попробуйте снова.", @"login.error.code",
                        @"Этот пароль не принят. Попробуйте снова.", @"login.error.password",
                        @"Не удалось войти. Попробуйте снова.", @"login.error.general",
                        @"Введите номер телефона, чтобы продолжить.", @"login.empty.phone",
                        @"Введите код входа из Telegram.", @"login.empty.code",
                        @"Введите пароль двухэтапной аутентификации.", @"login.empty.password",
                        @"Нет соединения. Подробности доступны в логах.", @"login.connection.unavailable",
                        @"О Telegraphica", @"about.title",
                        @"Версия %@ (%@)", @"about.version",
                        @"Все права защищены.", @"about.rights",
                        @"Автор: Yura Menschikov", @"about.author",
                        @"Проект на GitHub", @"about.project",
                        nil];
    NSDictionary *be = [NSDictionary dictionaryWithObjectsAndKeys:
                        @"Чаты", @"chats",
                        @"Усе чаты", @"drawer.all",
                        @"Усе чаты", @"drawer.all.tooltip",
                        @"Замацаванае паведамленне", @"pinned.title",
                        @"Профіль", @"profile",
                        @"Налады", @"settings",
                        @"Паведамленне", @"message",
                        @"Паведамленне", @"message.placeholder",
                        @"Вы", @"message.you",
                        @"Адказ", @"reply",
                        @"Адказ для %@", @"reply.to",
                        @"Адказ сабе", @"reply.toSelf",
                        @"Пераслана ад %@", @"forwarded.from",
                        @"Арыгінальнае паведамленне", @"message.original",
                        @"Выява", @"media.image",
                        @"Відэа", @"media.video",
                        @"GIF", @"media.gif",
                        @"Дакумент", @"media.document",
                        @"Медыя", @"media.media",
                        @"Стыкер", @"media.sticker",
                        @"Галасавое паведамленне", @"media.voice",
                        @"Відэапаведамленне", @"media.videoNote",
                        @"Сэрвіснае паведамленне", @"media.service",
                        @"Тэкст", @"media.text",
                        @"Прымацаваць фота", @"attach.photo",
                        @"Стыкеры", @"stickers",
                        @"Голас", @"voice",
                        @"Адправіць", @"send",
                        @"Скасаваць", @"cancel",
                        @"Дадаць подпіс...", @"caption.placeholder",
                        @"Паказваць апавяшчэнні", @"settings.notifications",
                        @"Гук апавяшчэнняў", @"settings.sound",
                        @"Бэйдж непрачытаных у Dock", @"settings.badge",
                        @"Паказваць тэкст паведамлення", @"settings.preview",
                        @"Апавяшчаць, калі Telegraphica адкрыта", @"settings.whenActive",
                        @"Схаваць бакавую панэль", @"settings.drawer",
                        @"Паказваць, калі суразмоўца друкуе", @"settings.typing",
                        @"Катэгорыя", @"settings.theme.category",
                        @"Светлыя тэмы", @"settings.theme.category.light",
                        @"Цёмныя тэмы", @"settings.theme.category.dark",
                        @"Retro", @"settings.theme.category.oldSchool",
                        @"Эксперыментальныя", @"settings.theme.category.experimental",
                        @"Тэма", @"settings.theme",
                        @"Афармленне", @"settings.appearance",
                        @"Папка загрузак", @"settings.downloads",
                        @"Мова", @"settings.language",
                        @"Паведамленні блокамі", @"settings.messages.blocks",
                        @"Памер тэксту", @"settings.chatText",
                        @"Малы", @"settings.chatText.small",
                        @"Звычайны", @"settings.chatText.normal",
                        @"Вялікі", @"settings.chatText.large",
                        @"Вельмі вялікі", @"settings.chatText.veryLarge",
                        @"Праверыць абнаўленні", @"settings.update",
                        @"Дыягнастычныя логі", @"settings.logs",
                        @"Пра Telegraphica", @"settings.about",
                        @"Апавяшчэнні", @"settings.section.notifications",
                        @"Агульныя", @"settings.section.drawer",
                        @"Рэсурсы", @"settings.section.resources",
                        @"Актыўныя сеансы", @"settings.section.sessions",
                        @"Інтэрфейс", @"settings.section.interface",
                        @"Файлы", @"settings.section.files",
                        @"Даведка", @"settings.section.help",
                        @"Выберыце папку, у якой будуць захоўвацца спампаваныя файлы", @"settings.downloads.help",
                        @"Прылады, на якіх выкананы ўваход у гэты акаўнт", @"settings.sessions.help",
                        @"Эканомны рэжым", @"settings.resources.economy",
                        @"Аўтазагрузка фота", @"settings.resources.photos",
                        @"Аўтазагрузка відэа", @"settings.resources.videos",
                        @"Аўтазагрузка дакументаў", @"settings.resources.documents",
                        @"Аўтапрайграванне аніміраваных стыкераў", @"settings.resources.autoplay",
                        @"Спыняць анімацыі, калі акно неактыўнае", @"settings.resources.stopInactive",
                        @"Максімальны памер аўтазагрузкі", @"settings.resources.maxDownload",
                        @"Актыўных анімацый", @"settings.resources.maxAnimations",
                        @"Ліміт медыякэшу", @"settings.resources.cacheLimit",
                        @"Эканомны рэжым памяншае аўтазагрузку, адключае лішнія анімацыі і зніжае памер кэшу. Асобныя пункты можна змяняць уручную.", @"settings.resources.hint",
                        @"Адкрыць актыўныя сеансы", @"settings.sessions.open",
                        @"Абнавіць", @"settings.sessions.refresh",
                        @"Загрузка актыўных сеансаў...", @"settings.sessions.loading",
                        @"Сеансы недаступныя: %@", @"settings.sessions.failed",
                        @"Спіс сеансаў састарэў. Абнаўляю...", @"settings.sessions.stale",
                        @"Актыўных прылад: %lu", @"settings.sessions.count",
                        @"Аўтазавяршэнне неактыўных сеансаў: %ld дз.", @"settings.sessions.ttl",
                        @"Апошняя актыўнасць: %@", @"settings.sessions.lastActive",
                        @"Невядомая прылада", @"settings.sessions.unknownDevice",
                        @"невядомая памылка", @"settings.sessions.unknownError",
                        @"Бягучая прылада", @"settings.sessions.current",
                        @"Няма іншых актыўных сеансаў", @"settings.sessions.empty",
                        @"Завяршыць", @"settings.sessions.terminate",
                        @"Завяршыць сеанс", @"settings.sessions.terminate.title",
                        @"Завяршыць сеанс на прыладзе «%@»?", @"settings.sessions.terminate.message",
                        @"Завяршэнне сеанса...", @"settings.sessions.terminating",
                        @"Сеанс завершаны.", @"settings.sessions.terminate.done",
                        @"Не атрымалася завяршыць сеанс: %@", @"settings.sessions.terminate.failed",
                        @"Выкарыстанне памяці", @"storage.open",
                        @"Выкарыстанне памяці", @"storage.title",
                        @"Загрузка...", @"storage.loading",
                        @"Усяго: %@", @"storage.total",
                        @"Файлы", @"storage.files",
                        @"База TDLib", @"storage.database",
                        @"Моўныя пакеты", @"storage.language",
                        @"Логі", @"storage.logs",
                        @"Медыя і дакументы застануцца ў воблаку Telegram, пры неабходнасці іх можна спампаваць зноў.", @"storage.safeHint",
                        @"Ачысціць кэш", @"storage.clear",
                        @"Абнавіць", @"storage.refresh",
                        @"Статыстыка недаступная", @"storage.unavailable",
                        @"Ачышчаем кэш...", @"storage.clearing",
                        @"Не атрымалася ачысціць кэш", @"storage.clearFailed",
                        @"Кэш ачышчаны. Абноўлены памер паказаны вышэй.", @"storage.clearDone",
                        @"Ачысціць кэш Telegraphica?", @"storage.confirm.title",
                        @"Спампаваныя медыя будуць выдалены з гэтага Mac, але застануцца ў Telegram. Аўтарызацыя і паведамленні не будуць закрануты.", @"storage.confirm.message",
                        @"Выдаліць лакальныя даныя", @"settings.localData.delete",
                        @"Выдаліць лакальныя даныя Telegraphica?", @"settings.localData.confirm.title",
                        @"Будзе выдалена лакальная база TDLib, кэш, прэв'ю, чарнавікі, дыягнастычныя логі і лакальны ключ базы на гэтым Mac. Даныя ў воблаку Telegram і файлы ў Downloads не будуць закрануты. Пасля гэтага трэба будзе ўвайсці зноў.", @"settings.localData.confirm.message",
                        @"Лакальныя даныя выдалены. Telegraphica вернецца да экрана ўваходу.", @"settings.localData.done",
                        @"Лакальныя даныя выдалены, але частка ачысткі не завяршылася: %@", @"settings.localData.partial",
                        @"Выдаленне лакальных даных...", @"settings.localData.busy",
                        @"Закрыць", @"close",
                        @"Новае паведамленне", @"notification.hiddenPreview",
                        @"Пачаць запіс голасу?", @"voice.permission.title",
                        @"Telegraphica зможа выкарыстоўваць мікрафон для запісу галасавых паведамленняў. Запіс пачынаецца толькі пасля націску кнопкі голасу.", @"voice.permission.message",
                        @"Запісваецца...", @"voice.recording",
                        @"Націсніце кнопку голасу яшчэ раз, каб спыніць запіс", @"voice.stopHint",
                        @"Адпраўка...", @"sending",
                        @"Адзначыць прачытаным", @"chat.markRead",
                        @"Прачытаць усе чаты", @"chat.readAll",
                        @"Замацаваць дыялог", @"chat.pin",
                        @"Адмацаваць дыялог", @"chat.unpin",
                        @"Уключыць лакальныя апавяшчэнні", @"chat.notifications.enable",
                        @"Адключыць апавяшчэнні", @"chat.notifications.mute",
                        @"На 1 гадзіну", @"chat.notifications.hour",
                        @"На 1 дзень", @"chat.notifications.day",
                        @"Назаўсёды", @"chat.notifications.forever",
                        @"Замацаваць паведамленне", @"message.pin",
                        @"Адмацаваць паведамленне", @"message.unpin",
                        @"Адказаць", @"message.reply",
                        @"Пераслаць...", @"message.forward",
                        @"Пераслаць у Выбранае", @"message.forward.saved",
                        @"Адкрыць каментары", @"message.comments.open",
                        @"Пракаментаваць", @"message.comments.add",
                        @"%ld каментар", @"message.comments.count.one",
                        @"%ld каментароў", @"message.comments.count.many",
                        @"каментары", @"message.comments.threadSuffix",
                        @"Каментары", @"message.comments.threadTitle",
                        @"Хто прачытаў", @"message.whoRead",
                        @"Хто прачытаў гэта паведамленне", @"message.viewers.title",
                        @"Загружаем чытачоў...", @"message.viewers.loading",
                        @"Чытачы недаступныя для гэтага паведамлення.", @"message.viewers.unavailable",
                        @"Ніхто яшчэ не прачытаў", @"message.viewers.empty",
                        @"Уваход яшчэ не гатовы", @"message.viewers.signInUnavailable",
                        @"Невядома", @"message.viewers.unknown",
                        @"Няма даных", @"message.viewers.noData",
                        @"Яшчэ рэакцыі", @"message.reactions.more",
                        @"Скапіяваць тэкст", @"message.copyText",
                        @"Скапіяваць неадпраўлены тэкст", @"message.copyUnsentText",
                        @"Паўтарыць адпраўку", @"message.retrySend",
                        @"Адпраўка не атрымалася", @"message.sendFailed",
                        @"Паўтарыць адпраўку?", @"message.retry.confirm.title",
                        @"Паведамленне магло быць адпраўлена, але Telegraphica не атрымала пацвярджэнне. Паўтор можа стварыць дубль.", @"message.retry.confirm.message",
                        @"Пацверджана частак: %lu з %lu. Паўтор можа стварыць дублі ўжо адпраўленых частак.", @"message.retry.confirm.partial",
                        @"Паўтараем адпраўку...", @"message.retry.sending",
                        @"Паведамленне адпраўлена", @"message.retry.sent",
                        @"Паўтор не атрымаўся", @"message.retry.failed",
                        @"Спампаваць медыя", @"message.downloadMedia",
                        @"Спампаваць дакумент", @"message.downloadDocument",
                        @"Спампаваць", @"message.download.action",
                        @"Рэдагаваць", @"message.edit",
                        @"Рэдагаваць паведамленне", @"message.edit.title",
                        @"Выпраўце тэкст і захавайце змены.", @"message.edit.hint",
                        @"Захаваць", @"message.edit.save",
                        @"Выдаліць паведамленне", @"message.delete",
                        @"Выдаліць паведамленне?", @"message.delete.title",
                        @"Гэта дзеянне нельга адмяніць.", @"message.delete.hint",
                        @"Выдаліць у мяне", @"message.delete.self",
                        @"Выдаліць ва ўсіх", @"message.delete.everyone",
                        @"Галасаваць", @"message.poll.vote",
                        @"Варыянт %lu", @"message.poll.optionFallback",
                        @"Няма варыянтаў", @"message.poll.noOptions",
                        @"Адпраўляем голас...", @"message.poll.sending",
                        @"Голас улічаны", @"message.poll.sent",
                        @"Не ўдалося прагаласаваць", @"message.poll.failed",
                        @"%ld голас", @"message.poll.votes.one",
                        @"%ld галасоў", @"message.poll.votes.many",
                        @"Пошук чатаў", @"search.chats.title",
                        @"Чат, група, чалавек", @"search.chats.placeholder",
                        @"Нядаўнія чаты з'явяцца тут", @"search.chats.emptyRecent",
                        @"Чаты не знойдзены", @"search.chats.empty",
                        @"Нядаўнія чаты. Увядзіце запыт, каб знайсці чат, групу ці чалавека.", @"search.chats.recent",
                        @"Загружаем нядаўнія чаты...", @"search.chats.loadingRecent",
                        @"Шукаем чаты...", @"search.chats.searching",
                        @"Загружана супадзенняў: %lu. Шукаем далей...", @"search.chats.loadedSearching",
                        @"Знойдзена чатаў: %lu", @"search.chats.found",
                        @"Пошук не атрымаўся: %@", @"search.chats.failed",
                        @"Загружаных чатаў пакуль няма", @"search.chats.noLoaded",
                        @"Адкрыць чат", @"search.chats.openHint",
                        @"Чат", @"search.chats.fallbackChat",
                        @"Выбранае", @"savedMessages",
                        @"Новая версія Telegraphica", @"update.title",
                        @"Адкрыць старонку загрузкі", @"update.open",
                        @"Не зараз", @"update.later",
                        @"Спампаваць абнаўленне", @"update.download",
                        @"Абнаўленняў няма", @"update.none",
                        @"Усталявана версія %@", @"update.noneMessage",
                        @"Даступная версія %@. Спампаваць усталёўшчык абнаўлення?", @"update.availableMessage",
                        @"Не атрымалася праверыць абнаўленні: %@", @"update.failed",
                        @"Абнаўленне спампавана", @"update.downloaded.title",
                        @"Файл захаваны: %@", @"update.downloaded.message",
                        @"Адкрыць усталёўшчык", @"update.downloaded.open",
                        @"Не атрымалася спампаваць абнаўленне", @"update.download.failed.title",
                        @"Памылка загрузкі: %@. Можна адкрыць старонку рэлізу і спампаваць файл уручную.", @"update.download.failed.message",
                        @"Профіль", @"profile.title",
                        @"Профіль", @"profile.fallback",
                        @"Пра сябе", @"profile.about",
                        @"Акаўнт", @"profile.account",
                        @"Імя карыстальніка", @"profile.username",
                        @"Тэлефон", @"profile.phone",
                        @"Telegram ID", @"profile.id",
                        @"Выйсці", @"profile.logout",
                        @"Абнавіць профіль", @"profile.refresh",
                        @"Увайсці", @"login.title",
                        @"Увядзіце нумар тэлефона, звязаны з акаўнтам Telegram, разам з кодам краіны.", @"login.phone.hint",
                        @"Нумар тэлефона", @"login.phone.label",
                        @"Увядзіце код", @"login.code.title",
                        @"Код прыйдзе ў Telegram. Увядзіце яго тут, каб працягнуць уваход.", @"login.code.hint",
                        @"Код уваходу", @"login.code.label",
                        @"Двухэтапная аўтэнтыфікацыя", @"login.password.title",
                        @"Увядзіце воблачны пароль Telegram. Telegraphica не запісвае яго ў логі.", @"login.password.hint",
                        @"Пароль", @"login.password.label",
                        @"Адправіць", @"login.send",
                        @"Адпраўка...", @"login.sending",
                        @"Логі", @"login.logs",
                        @"Статус", @"login.status",
                        @"Падключэнне", @"login.connecting.title",
                        @"Telegraphica ўсталёўвае бяспечнае злучэнне з Telegram. Гэта можа заняць некалькі секунд.", @"login.connecting.hint",
                        @"Завяршаем папярэднюю сесію і рыхтуем новы ўваход.", @"login.recovering.hint",
                        @"Паўтарыць", @"login.retry",
                        @"Не атрымалася падрыхтаваць уваход", @"login.config.title",
                        @"У гэтай зборцы адсутнічае ўнутраная канфігурацыя падключэння. Падрабязнасці даступныя ў логах.", @"login.config.missing",
                        @"Праверце нумар тэлефона і паспрабуйце зноў.", @"login.error.phone",
                        @"Гэты код не прыняты. Праверце Telegram і паспрабуйце зноў.", @"login.error.code",
                        @"Гэты пароль не прыняты. Паспрабуйце зноў.", @"login.error.password",
                        @"Не атрымалася ўвайсці. Паспрабуйце зноў.", @"login.error.general",
                        @"Увядзіце нумар тэлефона, каб працягнуць.", @"login.empty.phone",
                        @"Увядзіце код уваходу з Telegram.", @"login.empty.code",
                        @"Увядзіце пароль двухэтапнай аўтэнтыфікацыі.", @"login.empty.password",
                        @"Няма злучэння. Падрабязнасці даступныя ў логах.", @"login.connection.unavailable",
                        @"Пра Telegraphica", @"about.title",
                        @"Версія %@ (%@)", @"about.version",
                        @"Усе правы абаронены.", @"about.rights",
                        @"Аўтар: Yura Menschikov", @"about.author",
                        @"Праект на GitHub", @"about.project",
                        nil];
    NSDictionary *en = [NSDictionary dictionaryWithObjectsAndKeys:
                        @"Chats", @"chats",
                        @"All chats", @"drawer.all",
                        @"All chats", @"drawer.all.tooltip",
                        @"Pinned message", @"pinned.title",
                        @"Profile", @"profile",
                        @"Settings", @"settings",
                        @"Message", @"message",
                        @"Message", @"message.placeholder",
                        @"You", @"message.you",
                        @"Reply", @"reply",
                        @"Reply to %@", @"reply.to",
                        @"Reply to yourself", @"reply.toSelf",
                        @"Forwarded from %@", @"forwarded.from",
                        @"Original message", @"message.original",
                        @"Image", @"media.image",
                        @"Video", @"media.video",
                        @"GIF", @"media.gif",
                        @"Document", @"media.document",
                        @"Media", @"media.media",
                        @"Sticker", @"media.sticker",
                        @"Voice message", @"media.voice",
                        @"Video note", @"media.videoNote",
                        @"Service message", @"media.service",
                        @"Text", @"media.text",
                        @"Attach photo", @"attach.photo",
                        @"Stickers", @"stickers",
                        @"Voice", @"voice",
                        @"Send", @"send",
                        @"Cancel", @"cancel",
                        @"Add a caption...", @"caption.placeholder",
                        @"Show message notifications", @"settings.notifications",
                        @"Play notification sound", @"settings.sound",
                        @"Show unread badge in Dock", @"settings.badge",
                        @"Show message preview", @"settings.preview",
                        @"Notify while Telegraphica is active", @"settings.whenActive",
                        @"Hide side drawer", @"settings.drawer",
                        @"Show when someone is typing", @"settings.typing",
                        @"Category", @"settings.theme.category",
                        @"Light themes", @"settings.theme.category.light",
                        @"Dark themes", @"settings.theme.category.dark",
                        @"Retro", @"settings.theme.category.oldSchool",
                        @"Experimental", @"settings.theme.category.experimental",
                        @"Theme", @"settings.theme",
                        @"Appearance", @"settings.appearance",
                        @"Downloads folder", @"settings.downloads",
                        @"Language", @"settings.language",
                        @"Messages as blocks", @"settings.messages.blocks",
                        @"Text size", @"settings.chatText",
                        @"Small", @"settings.chatText.small",
                        @"Normal", @"settings.chatText.normal",
                        @"Large", @"settings.chatText.large",
                        @"Very large", @"settings.chatText.veryLarge",
                        @"Check for Updates", @"settings.update",
                        @"Diagnostic Logs", @"settings.logs",
                        @"About Telegraphica", @"settings.about",
                        @"Notifications", @"settings.section.notifications",
                        @"General", @"settings.section.drawer",
                        @"Resources", @"settings.section.resources",
                        @"Active Sessions", @"settings.section.sessions",
                        @"Interface", @"settings.section.interface",
                        @"Files", @"settings.section.files",
                        @"Help", @"settings.section.help",
                        @"Choose where downloaded files will be saved", @"settings.downloads.help",
                        @"Devices currently signed in to this account", @"settings.sessions.help",
                        @"Economy mode", @"settings.resources.economy",
                        @"Auto-download photos", @"settings.resources.photos",
                        @"Auto-download videos", @"settings.resources.videos",
                        @"Auto-download documents", @"settings.resources.documents",
                        @"Autoplay animated stickers", @"settings.resources.autoplay",
                        @"Stop animations while the window is inactive", @"settings.resources.stopInactive",
                        @"Maximum auto-download size", @"settings.resources.maxDownload",
                        @"Active animations", @"settings.resources.maxAnimations",
                        @"Media cache limit", @"settings.resources.cacheLimit",
                        @"Economy mode reduces auto-downloads, disables extra animations, and keeps cache smaller. Individual values remain editable.", @"settings.resources.hint",
                        @"Open Active Sessions", @"settings.sessions.open",
                        @"Refresh", @"settings.sessions.refresh",
                        @"Loading active sessions...", @"settings.sessions.loading",
                        @"Sessions are unavailable: %@", @"settings.sessions.failed",
                        @"Session list is stale. Refreshing...", @"settings.sessions.stale",
                        @"Active devices: %lu", @"settings.sessions.count",
                        @"Inactive sessions expire after %ld days", @"settings.sessions.ttl",
                        @"Last active: %@", @"settings.sessions.lastActive",
                        @"Unknown device", @"settings.sessions.unknownDevice",
                        @"unknown error", @"settings.sessions.unknownError",
                        @"This device", @"settings.sessions.current",
                        @"No other active sessions", @"settings.sessions.empty",
                        @"Terminate", @"settings.sessions.terminate",
                        @"Terminate Session", @"settings.sessions.terminate.title",
                        @"Terminate the session on “%@”?", @"settings.sessions.terminate.message",
                        @"Terminating session...", @"settings.sessions.terminating",
                        @"Session terminated.", @"settings.sessions.terminate.done",
                        @"Could not terminate session: %@", @"settings.sessions.terminate.failed",
                        @"Storage Usage", @"storage.open",
                        @"Storage Usage", @"storage.title",
                        @"Loading...", @"storage.loading",
                        @"Total: %@", @"storage.total",
                        @"Files", @"storage.files",
                        @"TDLib database", @"storage.database",
                        @"Language packs", @"storage.language",
                        @"Logs", @"storage.logs",
                        @"Media and documents remain in Telegram cloud and can be downloaded again when needed.", @"storage.safeHint",
                        @"Clear Cache", @"storage.clear",
                        @"Refresh", @"storage.refresh",
                        @"Storage statistics unavailable", @"storage.unavailable",
                        @"Clearing cache...", @"storage.clearing",
                        @"Could not clear cache", @"storage.clearFailed",
                        @"Cache cleared. Updated storage usage is shown above.", @"storage.clearDone",
                        @"Clear Telegraphica cache?", @"storage.confirm.title",
                        @"Downloaded media will be removed from this Mac, but will remain in Telegram. Authorization and messages will not be touched.", @"storage.confirm.message",
                        @"Delete Local Data", @"settings.localData.delete",
                        @"Delete Telegraphica local data?", @"settings.localData.confirm.title",
                        @"This removes the local TDLib database, cache, previews, drafts, diagnostic logs, and local database key from this Mac. Telegram cloud data and files in Downloads are not touched. You will need to sign in again.", @"settings.localData.confirm.message",
                        @"Local data was deleted. Telegraphica will return to the sign-in screen.", @"settings.localData.done",
                        @"Local data was deleted, but part of cleanup did not finish: %@", @"settings.localData.partial",
                        @"Deleting local data...", @"settings.localData.busy",
                        @"Close", @"close",
                        @"New message", @"notification.hiddenPreview",
                        @"Start voice recording?", @"voice.permission.title",
                        @"Telegraphica can use the microphone to record voice messages. Recording starts only after you press the voice button.", @"voice.permission.message",
                        @"Recording...", @"voice.recording",
                        @"Press the voice button again to stop recording", @"voice.stopHint",
                        @"Sending...", @"sending",
                        @"Mark as read", @"chat.markRead",
                        @"Read all chats", @"chat.readAll",
                        @"Pin chat", @"chat.pin",
                        @"Unpin chat", @"chat.unpin",
                        @"Enable local notifications", @"chat.notifications.enable",
                        @"Mute notifications", @"chat.notifications.mute",
                        @"For 1 hour", @"chat.notifications.hour",
                        @"For 1 day", @"chat.notifications.day",
                        @"Forever", @"chat.notifications.forever",
                        @"Pin message", @"message.pin",
                        @"Unpin message", @"message.unpin",
                        @"Reply", @"message.reply",
                        @"Forward...", @"message.forward",
                        @"Forward to Saved Messages", @"message.forward.saved",
                        @"Open comments", @"message.comments.open",
                        @"Comment", @"message.comments.add",
                        @"%ld comment", @"message.comments.count.one",
                        @"%ld comments", @"message.comments.count.many",
                        @"comments", @"message.comments.threadSuffix",
                        @"Comments", @"message.comments.threadTitle",
                        @"Who read", @"message.whoRead",
                        @"Who read this message", @"message.viewers.title",
                        @"Loading readers...", @"message.viewers.loading",
                        @"Readers are unavailable for this message.", @"message.viewers.unavailable",
                        @"Nobody has read it yet", @"message.viewers.empty",
                        @"Sign in is not ready", @"message.viewers.signInUnavailable",
                        @"Unknown", @"message.viewers.unknown",
                        @"No data", @"message.viewers.noData",
                        @"More reactions", @"message.reactions.more",
                        @"Copy text", @"message.copyText",
                        @"Copy unsent text", @"message.copyUnsentText",
                        @"Retry send", @"message.retrySend",
                        @"Send failed", @"message.sendFailed",
                        @"Retry sending?", @"message.retry.confirm.title",
                        @"This message may already have been sent, but Telegraphica did not receive confirmation. Retrying can create a duplicate.", @"message.retry.confirm.message",
                        @"Confirmed parts: %lu of %lu. Retrying can duplicate the parts that were already sent.", @"message.retry.confirm.partial",
                        @"Retrying send...", @"message.retry.sending",
                        @"Message sent", @"message.retry.sent",
                        @"Retry failed", @"message.retry.failed",
                        @"Download media", @"message.downloadMedia",
                        @"Download document", @"message.downloadDocument",
                        @"Download", @"message.download.action",
                        @"Edit", @"message.edit",
                        @"Edit message", @"message.edit.title",
                        @"Update the text and save your changes.", @"message.edit.hint",
                        @"Save", @"message.edit.save",
                        @"Delete message", @"message.delete",
                        @"Delete this message?", @"message.delete.title",
                        @"This action cannot be undone.", @"message.delete.hint",
                        @"Delete for me", @"message.delete.self",
                        @"Delete for everyone", @"message.delete.everyone",
                        @"Vote", @"message.poll.vote",
                        @"Option %lu", @"message.poll.optionFallback",
                        @"No options", @"message.poll.noOptions",
                        @"Sending vote...", @"message.poll.sending",
                        @"Vote sent", @"message.poll.sent",
                        @"Could not vote", @"message.poll.failed",
                        @"%ld vote", @"message.poll.votes.one",
                        @"%ld votes", @"message.poll.votes.many",
                        @"Search chats", @"search.chats.title",
                        @"Chat, group, person", @"search.chats.placeholder",
                        @"Recent chats will appear here", @"search.chats.emptyRecent",
                        @"No chats found", @"search.chats.empty",
                        @"Recent chats. Type to filter by chat, group, or person.", @"search.chats.recent",
                        @"Loading recent chats...", @"search.chats.loadingRecent",
                        @"Searching chats...", @"search.chats.searching",
                        @"Loaded matches: %lu. Searching more...", @"search.chats.loadedSearching",
                        @"Found chats: %lu", @"search.chats.found",
                        @"Search failed: %@", @"search.chats.failed",
                        @"No loaded chats yet", @"search.chats.noLoaded",
                        @"Open chat", @"search.chats.openHint",
                        @"Chat", @"search.chats.fallbackChat",
                        @"Saved Messages", @"savedMessages",
                        @"New Telegraphica Version", @"update.title",
                        @"Open Download Page", @"update.open",
                        @"Not Now", @"update.later",
                        @"Download Update", @"update.download",
                        @"No Updates", @"update.none",
                        @"Version %@ is installed.", @"update.noneMessage",
                        @"Version %@ is available. Download the update installer?", @"update.availableMessage",
                        @"Could not check for updates: %@", @"update.failed",
                        @"Update Downloaded", @"update.downloaded.title",
                        @"Saved to: %@", @"update.downloaded.message",
                        @"Open Installer", @"update.downloaded.open",
                        @"Could Not Download Update", @"update.download.failed.title",
                        @"Download failed: %@. You can open the release page and download the file manually.", @"update.download.failed.message",
                        @"Profile", @"profile.title",
                        @"Profile", @"profile.fallback",
                        @"About", @"profile.about",
                        @"Account", @"profile.account",
                        @"Username", @"profile.username",
                        @"Phone", @"profile.phone",
                        @"Telegram ID", @"profile.id",
                        @"Logout", @"profile.logout",
                        @"Refresh Profile", @"profile.refresh",
                        @"Sign in", @"login.title",
                        @"Enter the phone number connected to your Telegram account, including country code.", @"login.phone.hint",
                        @"Phone number", @"login.phone.label",
                        @"Enter login code", @"login.code.title",
                        @"The code arrives in Telegram. Enter it here to continue sign-in.", @"login.code.hint",
                        @"Login code", @"login.code.label",
                        @"Two-step password", @"login.password.title",
                        @"Enter your Telegram cloud password. Telegraphica does not write it to logs.", @"login.password.hint",
                        @"Password", @"login.password.label",
                        @"Send", @"login.send",
                        @"Sending...", @"login.sending",
                        @"Logs", @"login.logs",
                        @"Status", @"login.status",
                        @"Connecting", @"login.connecting.title",
                        @"Telegraphica is establishing a secure Telegram connection. This can take a few seconds.", @"login.connecting.hint",
                        @"Finishing the previous session and preparing a fresh sign-in.", @"login.recovering.hint",
                        @"Try Again", @"login.retry",
                        @"Sign-in could not be prepared", @"login.config.title",
                        @"This build is missing its internal connection configuration. Details are available in Logs.", @"login.config.missing",
                        @"Check the phone number and try again.", @"login.error.phone",
                        @"That login code was not accepted. Check Telegram and try again.", @"login.error.code",
                        @"That password was not accepted. Try again.", @"login.error.password",
                        @"Sign-in was not accepted. Try again.", @"login.error.general",
                        @"Enter your phone number to continue.", @"login.empty.phone",
                        @"Enter the login code from Telegram.", @"login.empty.code",
                        @"Enter your two-step password.", @"login.empty.password",
                        @"Connection unavailable. Open Logs for details.", @"login.connection.unavailable",
                        @"About Telegraphica", @"about.title",
                        @"Version %@ (%@)", @"about.version",
                        @"All rights reserved.", @"about.rights",
                        @"Author: Yura Menschikov", @"about.author",
                        @"Project on GitHub", @"about.project",
                        nil];
    NSDictionary *dictionary = [language isEqualToString:@"be"] ? be : ([language isEqualToString:@"en"] ? en : ru);
    NSString *value = [dictionary objectForKey:key];
    return value ? value : key;
}
